#include "RegisterMonoModules.h"

extern bool gEnableGyroscope;

extern "C"
{
	typedef void* gpointer;
	typedef int gboolean;
#if !(TARGET_IPHONE_SIMULATOR)
	const char*			UnityIPhoneRuntimeVersion = "4.3.4f1";
	void				mono_dl_register_symbol (const char* name, void *addr);
	extern int 			mono_ficall_flag;
	void				mono_aot_register_module(gpointer *aot_info);
	extern gboolean		mono_aot_only;
	extern gpointer*	mono_aot_module_Assembly_CSharp_info; // Assembly-CSharp.dll
	extern gpointer*	mono_aot_module_Glow11_info; // Glow11.dll
	extern gpointer*	mono_aot_module_System_Core_info; // System.Core.dll
	extern gpointer*	mono_aot_module_System_info; // System.dll
	extern gpointer*	mono_aot_module_UnityEngine_info; // UnityEngine.dll
	extern gpointer*	mono_aot_module_mscorlib_info; // mscorlib.dll
#endif // !(TARGET_IPHONE_SIMULATOR)
}
void RegisterMonoModules()
{
    gEnableGyroscope = false;
#if !(TARGET_IPHONE_SIMULATOR)
	mono_aot_only = true;
	mono_ficall_flag = false;
	mono_aot_register_module(mono_aot_module_Assembly_CSharp_info);
	mono_aot_register_module(mono_aot_module_Glow11_info);
	mono_aot_register_module(mono_aot_module_System_Core_info);
	mono_aot_register_module(mono_aot_module_System_info);
	mono_aot_register_module(mono_aot_module_UnityEngine_info);
	mono_aot_register_module(mono_aot_module_mscorlib_info);

#endif // !(TARGET_IPHONE_SIMULATOR)
}

void RegisterAllStrippedInternalCalls ()
{
	void Register_UnityEngine_Animation_get_clip ();
	Register_UnityEngine_Animation_get_clip ();
	void Register_UnityEngine_Animation_set_clip ();
	Register_UnityEngine_Animation_set_clip ();
	void Register_UnityEngine_Animation_get_playAutomatically ();
	Register_UnityEngine_Animation_get_playAutomatically ();
	void Register_UnityEngine_Animation_set_playAutomatically ();
	Register_UnityEngine_Animation_set_playAutomatically ();
	void Register_UnityEngine_Animation_get_wrapMode ();
	Register_UnityEngine_Animation_get_wrapMode ();
	void Register_UnityEngine_Animation_set_wrapMode ();
	Register_UnityEngine_Animation_set_wrapMode ();
	void Register_UnityEngine_Animation_INTERNAL_CALL_Stop ();
	Register_UnityEngine_Animation_INTERNAL_CALL_Stop ();
	void Register_UnityEngine_Animation_Internal_StopByName ();
	Register_UnityEngine_Animation_Internal_StopByName ();
	void Register_UnityEngine_Animation_Internal_RewindByName ();
	Register_UnityEngine_Animation_Internal_RewindByName ();
	void Register_UnityEngine_Animation_INTERNAL_CALL_Rewind ();
	Register_UnityEngine_Animation_INTERNAL_CALL_Rewind ();
	void Register_UnityEngine_Animation_INTERNAL_CALL_Sample ();
	Register_UnityEngine_Animation_INTERNAL_CALL_Sample ();
	void Register_UnityEngine_Animation_get_isPlaying ();
	Register_UnityEngine_Animation_get_isPlaying ();
	void Register_UnityEngine_Animation_IsPlaying ();
	Register_UnityEngine_Animation_IsPlaying ();
	void Register_UnityEngine_Animation_Play ();
	Register_UnityEngine_Animation_Play ();
	void Register_UnityEngine_Animation_CrossFade ();
	Register_UnityEngine_Animation_CrossFade ();
	void Register_UnityEngine_Animation_Blend ();
	Register_UnityEngine_Animation_Blend ();
	void Register_UnityEngine_Animation_CrossFadeQueued ();
	Register_UnityEngine_Animation_CrossFadeQueued ();
	void Register_UnityEngine_Animation_PlayQueued ();
	Register_UnityEngine_Animation_PlayQueued ();
	void Register_UnityEngine_Animation_AddClip ();
	Register_UnityEngine_Animation_AddClip ();
	void Register_UnityEngine_Animation_RemoveClip ();
	Register_UnityEngine_Animation_RemoveClip ();
	void Register_UnityEngine_Animation_GetClipCount ();
	Register_UnityEngine_Animation_GetClipCount ();
	void Register_UnityEngine_Animation_RemoveClip2 ();
	Register_UnityEngine_Animation_RemoveClip2 ();
	void Register_UnityEngine_Animation_PlayDefaultAnimation ();
	Register_UnityEngine_Animation_PlayDefaultAnimation ();
	void Register_UnityEngine_Animation_INTERNAL_CALL_SyncLayer ();
	Register_UnityEngine_Animation_INTERNAL_CALL_SyncLayer ();
	void Register_UnityEngine_Animation_GetState ();
	Register_UnityEngine_Animation_GetState ();
	void Register_UnityEngine_Animation_GetStateAtIndex ();
	Register_UnityEngine_Animation_GetStateAtIndex ();
	void Register_UnityEngine_Animation_GetStateCount ();
	Register_UnityEngine_Animation_GetStateCount ();
	void Register_UnityEngine_Animation_get_animatePhysics ();
	Register_UnityEngine_Animation_get_animatePhysics ();
	void Register_UnityEngine_Animation_set_animatePhysics ();
	Register_UnityEngine_Animation_set_animatePhysics ();
	void Register_UnityEngine_Animation_get_animateOnlyIfVisible ();
	Register_UnityEngine_Animation_get_animateOnlyIfVisible ();
	void Register_UnityEngine_Animation_set_animateOnlyIfVisible ();
	Register_UnityEngine_Animation_set_animateOnlyIfVisible ();
	void Register_UnityEngine_Animation_get_cullingType ();
	Register_UnityEngine_Animation_get_cullingType ();
	void Register_UnityEngine_Animation_set_cullingType ();
	Register_UnityEngine_Animation_set_cullingType ();
	void Register_UnityEngine_Animation_INTERNAL_get_localBounds ();
	Register_UnityEngine_Animation_INTERNAL_get_localBounds ();
	void Register_UnityEngine_Animation_INTERNAL_set_localBounds ();
	Register_UnityEngine_Animation_INTERNAL_set_localBounds ();
	void Register_UnityEngine_AnimationClip_Internal_CreateAnimationClip ();
	Register_UnityEngine_AnimationClip_Internal_CreateAnimationClip ();
	void Register_UnityEngine_AnimationClip_get_length ();
	Register_UnityEngine_AnimationClip_get_length ();
	void Register_UnityEngine_AnimationClip_get_startTime ();
	Register_UnityEngine_AnimationClip_get_startTime ();
	void Register_UnityEngine_AnimationClip_get_stopTime ();
	Register_UnityEngine_AnimationClip_get_stopTime ();
	void Register_UnityEngine_AnimationClip_get_frameRate ();
	Register_UnityEngine_AnimationClip_get_frameRate ();
	void Register_UnityEngine_AnimationClip_set_frameRate ();
	Register_UnityEngine_AnimationClip_set_frameRate ();
	void Register_UnityEngine_AnimationClip_SetCurve ();
	Register_UnityEngine_AnimationClip_SetCurve ();
	void Register_UnityEngine_AnimationClip_INTERNAL_CALL_EnsureQuaternionContinuity ();
	Register_UnityEngine_AnimationClip_INTERNAL_CALL_EnsureQuaternionContinuity ();
	void Register_UnityEngine_AnimationClip_INTERNAL_CALL_ClearCurves ();
	Register_UnityEngine_AnimationClip_INTERNAL_CALL_ClearCurves ();
	void Register_UnityEngine_AnimationClip_get_wrapMode ();
	Register_UnityEngine_AnimationClip_get_wrapMode ();
	void Register_UnityEngine_AnimationClip_set_wrapMode ();
	Register_UnityEngine_AnimationClip_set_wrapMode ();
	void Register_UnityEngine_AnimationClip_AddEvent ();
	Register_UnityEngine_AnimationClip_AddEvent ();
	void Register_UnityEngine_AnimationClip_INTERNAL_get_localBounds ();
	Register_UnityEngine_AnimationClip_INTERNAL_get_localBounds ();
	void Register_UnityEngine_AnimationClip_INTERNAL_set_localBounds ();
	Register_UnityEngine_AnimationClip_INTERNAL_set_localBounds ();
	void Register_UnityEngine_AnimationCurve_Cleanup ();
	Register_UnityEngine_AnimationCurve_Cleanup ();
	void Register_UnityEngine_AnimationCurve_Evaluate ();
	Register_UnityEngine_AnimationCurve_Evaluate ();
	void Register_UnityEngine_AnimationCurve_AddKey ();
	Register_UnityEngine_AnimationCurve_AddKey ();
	void Register_UnityEngine_AnimationCurve_INTERNAL_CALL_AddKey_Internal ();
	Register_UnityEngine_AnimationCurve_INTERNAL_CALL_AddKey_Internal ();
	void Register_UnityEngine_AnimationCurve_INTERNAL_CALL_MoveKey ();
	Register_UnityEngine_AnimationCurve_INTERNAL_CALL_MoveKey ();
	void Register_UnityEngine_AnimationCurve_RemoveKey ();
	Register_UnityEngine_AnimationCurve_RemoveKey ();
	void Register_UnityEngine_AnimationCurve_get_length ();
	Register_UnityEngine_AnimationCurve_get_length ();
	void Register_UnityEngine_AnimationCurve_SetKeys ();
	Register_UnityEngine_AnimationCurve_SetKeys ();
	void Register_UnityEngine_AnimationCurve_GetKey_Internal ();
	Register_UnityEngine_AnimationCurve_GetKey_Internal ();
	void Register_UnityEngine_AnimationCurve_GetKeys ();
	Register_UnityEngine_AnimationCurve_GetKeys ();
	void Register_UnityEngine_AnimationCurve_SmoothTangents ();
	Register_UnityEngine_AnimationCurve_SmoothTangents ();
	void Register_UnityEngine_AnimationCurve_get_preWrapMode ();
	Register_UnityEngine_AnimationCurve_get_preWrapMode ();
	void Register_UnityEngine_AnimationCurve_set_preWrapMode ();
	Register_UnityEngine_AnimationCurve_set_preWrapMode ();
	void Register_UnityEngine_AnimationCurve_get_postWrapMode ();
	Register_UnityEngine_AnimationCurve_get_postWrapMode ();
	void Register_UnityEngine_AnimationCurve_set_postWrapMode ();
	Register_UnityEngine_AnimationCurve_set_postWrapMode ();
	void Register_UnityEngine_AnimationCurve_Init ();
	Register_UnityEngine_AnimationCurve_Init ();
	void Register_UnityEngine_AnimationEvent_Destroy ();
	Register_UnityEngine_AnimationEvent_Destroy ();
	void Register_UnityEngine_AnimationInfo_ClipInstanceToScriptingObject ();
	Register_UnityEngine_AnimationInfo_ClipInstanceToScriptingObject ();
	void Register_UnityEngine_AnimationState_get_time ();
	Register_UnityEngine_AnimationState_get_time ();
	void Register_UnityEngine_AnimationState_set_time ();
	Register_UnityEngine_AnimationState_set_time ();
	void Register_UnityEngine_AnimationState_get_speed ();
	Register_UnityEngine_AnimationState_get_speed ();
	void Register_UnityEngine_AnimationState_set_speed ();
	Register_UnityEngine_AnimationState_set_speed ();
	void Register_UnityEngine_AnimationState_get_length ();
	Register_UnityEngine_AnimationState_get_length ();
	void Register_UnityEngine_AnimationState_set_layer ();
	Register_UnityEngine_AnimationState_set_layer ();
	void Register_UnityEngine_AnimationState_get_clip ();
	Register_UnityEngine_AnimationState_get_clip ();
	void Register_UnityEngine_AnimationState_get_name ();
	Register_UnityEngine_AnimationState_get_name ();
	void Register_UnityEngine_Animator_StringToHash ();
	Register_UnityEngine_Animator_StringToHash ();
	void Register_UnityEngine_Application_Quit ();
	Register_UnityEngine_Application_Quit ();
	void Register_UnityEngine_Application_CancelQuit ();
	Register_UnityEngine_Application_CancelQuit ();
	void Register_UnityEngine_Application_get_loadedLevel ();
	Register_UnityEngine_Application_get_loadedLevel ();
	void Register_UnityEngine_Application_get_loadedLevelName ();
	Register_UnityEngine_Application_get_loadedLevelName ();
	void Register_UnityEngine_Application_LoadLevelAsync ();
	Register_UnityEngine_Application_LoadLevelAsync ();
	void Register_UnityEngine_Application_get_isLoadingLevel ();
	Register_UnityEngine_Application_get_isLoadingLevel ();
	void Register_UnityEngine_Application_get_levelCount ();
	Register_UnityEngine_Application_get_levelCount ();
	void Register_UnityEngine_Application_GetStreamProgressForLevelByName ();
	Register_UnityEngine_Application_GetStreamProgressForLevelByName ();
	void Register_UnityEngine_Application_GetStreamProgressForLevel ();
	Register_UnityEngine_Application_GetStreamProgressForLevel ();
	void Register_UnityEngine_Application_get_streamedBytes ();
	Register_UnityEngine_Application_get_streamedBytes ();
	void Register_UnityEngine_Application_CanStreamedLevelBeLoadedByName ();
	Register_UnityEngine_Application_CanStreamedLevelBeLoadedByName ();
	void Register_UnityEngine_Application_CanStreamedLevelBeLoaded ();
	Register_UnityEngine_Application_CanStreamedLevelBeLoaded ();
	void Register_UnityEngine_Application_get_isPlaying ();
	Register_UnityEngine_Application_get_isPlaying ();
	void Register_UnityEngine_Application_get_isEditor ();
	Register_UnityEngine_Application_get_isEditor ();
	void Register_UnityEngine_Application_get_isWebPlayer ();
	Register_UnityEngine_Application_get_isWebPlayer ();
	void Register_UnityEngine_Application_get_platform ();
	Register_UnityEngine_Application_get_platform ();
	void Register_UnityEngine_Application_CaptureScreenshot ();
	Register_UnityEngine_Application_CaptureScreenshot ();
	void Register_UnityEngine_Application_get_runInBackground ();
	Register_UnityEngine_Application_get_runInBackground ();
	void Register_UnityEngine_Application_set_runInBackground ();
	Register_UnityEngine_Application_set_runInBackground ();
	void Register_UnityEngine_Application_HasProLicense ();
	Register_UnityEngine_Application_HasProLicense ();
	void Register_UnityEngine_Application_HasAdvancedLicense ();
	Register_UnityEngine_Application_HasAdvancedLicense ();
	void Register_UnityEngine_Application_DontDestroyOnLoad ();
	Register_UnityEngine_Application_DontDestroyOnLoad ();
	void Register_UnityEngine_Application_get_dataPath ();
	Register_UnityEngine_Application_get_dataPath ();
	void Register_UnityEngine_Application_get_streamingAssetsPath ();
	Register_UnityEngine_Application_get_streamingAssetsPath ();
	void Register_UnityEngine_Application_get_persistentDataPath ();
	Register_UnityEngine_Application_get_persistentDataPath ();
	void Register_UnityEngine_Application_get_temporaryCachePath ();
	Register_UnityEngine_Application_get_temporaryCachePath ();
	void Register_UnityEngine_Application_get_srcValue ();
	Register_UnityEngine_Application_get_srcValue ();
	void Register_UnityEngine_Application_get_absoluteURL ();
	Register_UnityEngine_Application_get_absoluteURL ();
	void Register_UnityEngine_Application_Internal_ExternalCall ();
	Register_UnityEngine_Application_Internal_ExternalCall ();
	void Register_UnityEngine_Application_get_unityVersion ();
	Register_UnityEngine_Application_get_unityVersion ();
	void Register_UnityEngine_Application_GetBuildUnityVersion ();
	Register_UnityEngine_Application_GetBuildUnityVersion ();
	void Register_UnityEngine_Application_GetNumericUnityVersion ();
	Register_UnityEngine_Application_GetNumericUnityVersion ();
	void Register_UnityEngine_Application_get_webSecurityEnabled ();
	Register_UnityEngine_Application_get_webSecurityEnabled ();
	void Register_UnityEngine_Application_get_webSecurityHostUrl ();
	Register_UnityEngine_Application_get_webSecurityHostUrl ();
	void Register_UnityEngine_Application_OpenURL ();
	Register_UnityEngine_Application_OpenURL ();
	void Register_UnityEngine_Application_CommitSuicide ();
	Register_UnityEngine_Application_CommitSuicide ();
	void Register_UnityEngine_Application_get_targetFrameRate ();
	Register_UnityEngine_Application_get_targetFrameRate ();
	void Register_UnityEngine_Application_set_targetFrameRate ();
	Register_UnityEngine_Application_set_targetFrameRate ();
	void Register_UnityEngine_Application_get_systemLanguage ();
	Register_UnityEngine_Application_get_systemLanguage ();
	void Register_UnityEngine_Application_SetLogCallbackDefined ();
	Register_UnityEngine_Application_SetLogCallbackDefined ();
	void Register_UnityEngine_Application_get_backgroundLoadingPriority ();
	Register_UnityEngine_Application_get_backgroundLoadingPriority ();
	void Register_UnityEngine_Application_set_backgroundLoadingPriority ();
	Register_UnityEngine_Application_set_backgroundLoadingPriority ();
	void Register_UnityEngine_Application_get_internetReachability ();
	Register_UnityEngine_Application_get_internetReachability ();
	void Register_UnityEngine_Application_get_genuine ();
	Register_UnityEngine_Application_get_genuine ();
	void Register_UnityEngine_Application_get_genuineCheckAvailable ();
	Register_UnityEngine_Application_get_genuineCheckAvailable ();
	void Register_UnityEngine_Application_RequestUserAuthorization ();
	Register_UnityEngine_Application_RequestUserAuthorization ();
	void Register_UnityEngine_Application_HasUserAuthorization ();
	Register_UnityEngine_Application_HasUserAuthorization ();
	void Register_UnityEngine_Application_ReplyToUserAuthorizationRequest ();
	Register_UnityEngine_Application_ReplyToUserAuthorizationRequest ();
	void Register_UnityEngine_Application_GetUserAuthorizationRequestMode_Internal ();
	Register_UnityEngine_Application_GetUserAuthorizationRequestMode_Internal ();
	void Register_UnityEngine_AssetBundleCreateRequest_get_assetBundle ();
	Register_UnityEngine_AssetBundleCreateRequest_get_assetBundle ();
	void Register_UnityEngine_AssetBundleCreateRequest_DisableCompatibilityChecks ();
	Register_UnityEngine_AssetBundleCreateRequest_DisableCompatibilityChecks ();
	void Register_UnityEngine_AsyncOperation_InternalDestroy ();
	Register_UnityEngine_AsyncOperation_InternalDestroy ();
	void Register_UnityEngine_AudioClip_get_length ();
	Register_UnityEngine_AudioClip_get_length ();
	void Register_UnityEngine_AudioClip_get_samples ();
	Register_UnityEngine_AudioClip_get_samples ();
	void Register_UnityEngine_AudioClip_get_channels ();
	Register_UnityEngine_AudioClip_get_channels ();
	void Register_UnityEngine_AudioClip_get_frequency ();
	Register_UnityEngine_AudioClip_get_frequency ();
	void Register_UnityEngine_AudioClip_get_isReadyToPlay ();
	Register_UnityEngine_AudioClip_get_isReadyToPlay ();
	void Register_UnityEngine_AudioClip_GetData ();
	Register_UnityEngine_AudioClip_GetData ();
	void Register_UnityEngine_AudioClip_SetData ();
	Register_UnityEngine_AudioClip_SetData ();
	void Register_UnityEngine_AudioClip_Construct_Internal ();
	Register_UnityEngine_AudioClip_Construct_Internal ();
	void Register_UnityEngine_AudioClip_Init_Internal ();
	Register_UnityEngine_AudioClip_Init_Internal ();
	void Register_UnityEngine_AudioSource_get_volume ();
	Register_UnityEngine_AudioSource_get_volume ();
	void Register_UnityEngine_AudioSource_set_volume ();
	Register_UnityEngine_AudioSource_set_volume ();
	void Register_UnityEngine_AudioSource_set_pitch ();
	Register_UnityEngine_AudioSource_set_pitch ();
	void Register_UnityEngine_AudioSource_set_clip ();
	Register_UnityEngine_AudioSource_set_clip ();
	void Register_UnityEngine_AudioSource_Play ();
	Register_UnityEngine_AudioSource_Play ();
	void Register_UnityEngine_AudioSource_Stop ();
	Register_UnityEngine_AudioSource_Stop ();
	void Register_UnityEngine_AudioSource_get_isPlaying ();
	Register_UnityEngine_AudioSource_get_isPlaying ();
	void Register_UnityEngine_AudioSource_PlayOneShot ();
	Register_UnityEngine_AudioSource_PlayOneShot ();
	void Register_UnityEngine_AudioSource_set_loop ();
	Register_UnityEngine_AudioSource_set_loop ();
	void Register_UnityEngine_AudioSource_set_priority ();
	Register_UnityEngine_AudioSource_set_priority ();
	void Register_UnityEngine_Behaviour_get_enabled ();
	Register_UnityEngine_Behaviour_get_enabled ();
	void Register_UnityEngine_Behaviour_set_enabled ();
	Register_UnityEngine_Behaviour_set_enabled ();
	void Register_UnityEngine_BoxCollider_INTERNAL_get_center ();
	Register_UnityEngine_BoxCollider_INTERNAL_get_center ();
	void Register_UnityEngine_BoxCollider_INTERNAL_set_center ();
	Register_UnityEngine_BoxCollider_INTERNAL_set_center ();
	void Register_UnityEngine_BoxCollider_INTERNAL_get_size ();
	Register_UnityEngine_BoxCollider_INTERNAL_get_size ();
	void Register_UnityEngine_BoxCollider_INTERNAL_set_size ();
	Register_UnityEngine_BoxCollider_INTERNAL_set_size ();
	void Register_UnityEngine_Camera_get_fieldOfView ();
	Register_UnityEngine_Camera_get_fieldOfView ();
	void Register_UnityEngine_Camera_set_fieldOfView ();
	Register_UnityEngine_Camera_set_fieldOfView ();
	void Register_UnityEngine_Camera_get_nearClipPlane ();
	Register_UnityEngine_Camera_get_nearClipPlane ();
	void Register_UnityEngine_Camera_set_nearClipPlane ();
	Register_UnityEngine_Camera_set_nearClipPlane ();
	void Register_UnityEngine_Camera_get_farClipPlane ();
	Register_UnityEngine_Camera_get_farClipPlane ();
	void Register_UnityEngine_Camera_set_farClipPlane ();
	Register_UnityEngine_Camera_set_farClipPlane ();
	void Register_UnityEngine_Camera_set_renderingPath ();
	Register_UnityEngine_Camera_set_renderingPath ();
	void Register_UnityEngine_Camera_get_orthographicSize ();
	Register_UnityEngine_Camera_get_orthographicSize ();
	void Register_UnityEngine_Camera_set_orthographicSize ();
	Register_UnityEngine_Camera_set_orthographicSize ();
	void Register_UnityEngine_Camera_get_orthographic ();
	Register_UnityEngine_Camera_get_orthographic ();
	void Register_UnityEngine_Camera_set_orthographic ();
	Register_UnityEngine_Camera_set_orthographic ();
	void Register_UnityEngine_Camera_set_transparencySortMode ();
	Register_UnityEngine_Camera_set_transparencySortMode ();
	void Register_UnityEngine_Camera_get_depth ();
	Register_UnityEngine_Camera_get_depth ();
	void Register_UnityEngine_Camera_set_depth ();
	Register_UnityEngine_Camera_set_depth ();
	void Register_UnityEngine_Camera_get_cullingMask ();
	Register_UnityEngine_Camera_get_cullingMask ();
	void Register_UnityEngine_Camera_set_cullingMask ();
	Register_UnityEngine_Camera_set_cullingMask ();
	void Register_UnityEngine_Camera_get_eventMask ();
	Register_UnityEngine_Camera_get_eventMask ();
	void Register_UnityEngine_Camera_set_eventMask ();
	Register_UnityEngine_Camera_set_eventMask ();
	void Register_UnityEngine_Camera_INTERNAL_set_backgroundColor ();
	Register_UnityEngine_Camera_INTERNAL_set_backgroundColor ();
	void Register_UnityEngine_Camera_INTERNAL_get_rect ();
	Register_UnityEngine_Camera_INTERNAL_get_rect ();
	void Register_UnityEngine_Camera_INTERNAL_set_rect ();
	Register_UnityEngine_Camera_INTERNAL_set_rect ();
	void Register_UnityEngine_Camera_INTERNAL_get_pixelRect ();
	Register_UnityEngine_Camera_INTERNAL_get_pixelRect ();
	void Register_UnityEngine_Camera_get_targetTexture ();
	Register_UnityEngine_Camera_get_targetTexture ();
	void Register_UnityEngine_Camera_set_targetTexture ();
	Register_UnityEngine_Camera_set_targetTexture ();
	void Register_UnityEngine_Camera_SetTargetBuffersImpl ();
	Register_UnityEngine_Camera_SetTargetBuffersImpl ();
	void Register_UnityEngine_Camera_get_pixelWidth ();
	Register_UnityEngine_Camera_get_pixelWidth ();
	void Register_UnityEngine_Camera_get_pixelHeight ();
	Register_UnityEngine_Camera_get_pixelHeight ();
	void Register_UnityEngine_Camera_INTERNAL_get_projectionMatrix ();
	Register_UnityEngine_Camera_INTERNAL_get_projectionMatrix ();
	void Register_UnityEngine_Camera_INTERNAL_set_projectionMatrix ();
	Register_UnityEngine_Camera_INTERNAL_set_projectionMatrix ();
	void Register_UnityEngine_Camera_get_clearFlags ();
	Register_UnityEngine_Camera_get_clearFlags ();
	void Register_UnityEngine_Camera_set_clearFlags ();
	Register_UnityEngine_Camera_set_clearFlags ();
	void Register_UnityEngine_Camera_INTERNAL_CALL_WorldToScreenPoint ();
	Register_UnityEngine_Camera_INTERNAL_CALL_WorldToScreenPoint ();
	void Register_UnityEngine_Camera_INTERNAL_CALL_WorldToViewportPoint ();
	Register_UnityEngine_Camera_INTERNAL_CALL_WorldToViewportPoint ();
	void Register_UnityEngine_Camera_INTERNAL_CALL_ViewportToWorldPoint ();
	Register_UnityEngine_Camera_INTERNAL_CALL_ViewportToWorldPoint ();
	void Register_UnityEngine_Camera_INTERNAL_CALL_ScreenToWorldPoint ();
	Register_UnityEngine_Camera_INTERNAL_CALL_ScreenToWorldPoint ();
	void Register_UnityEngine_Camera_INTERNAL_CALL_ScreenToViewportPoint ();
	Register_UnityEngine_Camera_INTERNAL_CALL_ScreenToViewportPoint ();
	void Register_UnityEngine_Camera_INTERNAL_CALL_ScreenPointToRay ();
	Register_UnityEngine_Camera_INTERNAL_CALL_ScreenPointToRay ();
	void Register_UnityEngine_Camera_get_main ();
	Register_UnityEngine_Camera_get_main ();
	void Register_UnityEngine_Camera_get_allCameras ();
	Register_UnityEngine_Camera_get_allCameras ();
	void Register_UnityEngine_Camera_Render ();
	Register_UnityEngine_Camera_Render ();
	void Register_UnityEngine_Camera_SetReplacementShader ();
	Register_UnityEngine_Camera_SetReplacementShader ();
	void Register_UnityEngine_Camera_CopyFrom ();
	Register_UnityEngine_Camera_CopyFrom ();
	void Register_UnityEngine_CapsuleCollider_INTERNAL_get_center ();
	Register_UnityEngine_CapsuleCollider_INTERNAL_get_center ();
	void Register_UnityEngine_CapsuleCollider_INTERNAL_set_center ();
	Register_UnityEngine_CapsuleCollider_INTERNAL_set_center ();
	void Register_UnityEngine_CapsuleCollider_set_radius ();
	Register_UnityEngine_CapsuleCollider_set_radius ();
	void Register_UnityEngine_CharacterController_INTERNAL_CALL_SimpleMove ();
	Register_UnityEngine_CharacterController_INTERNAL_CALL_SimpleMove ();
	void Register_UnityEngine_CharacterController_INTERNAL_CALL_Move ();
	Register_UnityEngine_CharacterController_INTERNAL_CALL_Move ();
	void Register_UnityEngine_CharacterController_get_isGrounded ();
	Register_UnityEngine_CharacterController_get_isGrounded ();
	void Register_UnityEngine_Collider_get_enabled ();
	Register_UnityEngine_Collider_get_enabled ();
	void Register_UnityEngine_Collider_set_enabled ();
	Register_UnityEngine_Collider_set_enabled ();
	void Register_UnityEngine_Collider_get_attachedRigidbody ();
	Register_UnityEngine_Collider_get_attachedRigidbody ();
	void Register_UnityEngine_Collider_set_isTrigger ();
	Register_UnityEngine_Collider_set_isTrigger ();
	void Register_UnityEngine_Collider_INTERNAL_CALL_Internal_Raycast ();
	Register_UnityEngine_Collider_INTERNAL_CALL_Internal_Raycast ();
	void Register_UnityEngine_Collider2D_get_attachedRigidbody ();
	Register_UnityEngine_Collider2D_get_attachedRigidbody ();
	void Register_UnityEngine_Component_InternalGetTransform ();
	Register_UnityEngine_Component_InternalGetTransform ();
	void Register_UnityEngine_Component_get_rigidbody ();
	Register_UnityEngine_Component_get_rigidbody ();
	void Register_UnityEngine_Component_get_camera ();
	Register_UnityEngine_Component_get_camera ();
	void Register_UnityEngine_Component_get_light ();
	Register_UnityEngine_Component_get_light ();
	void Register_UnityEngine_Component_get_animation ();
	Register_UnityEngine_Component_get_animation ();
	void Register_UnityEngine_Component_get_renderer ();
	Register_UnityEngine_Component_get_renderer ();
	void Register_UnityEngine_Component_get_audio ();
	Register_UnityEngine_Component_get_audio ();
	void Register_UnityEngine_Component_get_guiText ();
	Register_UnityEngine_Component_get_guiText ();
	void Register_UnityEngine_Component_get_collider ();
	Register_UnityEngine_Component_get_collider ();
	void Register_UnityEngine_Component_get_particleEmitter ();
	Register_UnityEngine_Component_get_particleEmitter ();
	void Register_UnityEngine_Component_get_particleSystem ();
	Register_UnityEngine_Component_get_particleSystem ();
	void Register_UnityEngine_Component_InternalGetGameObject ();
	Register_UnityEngine_Component_InternalGetGameObject ();
	void Register_UnityEngine_Component_GetComponent ();
	Register_UnityEngine_Component_GetComponent ();
	void Register_UnityEngine_Component_GetComponentsWithCorrectReturnType ();
	Register_UnityEngine_Component_GetComponentsWithCorrectReturnType ();
	void Register_UnityEngine_Component_SendMessage ();
	Register_UnityEngine_Component_SendMessage ();
	void Register_UnityEngine_Component_BroadcastMessage ();
	Register_UnityEngine_Component_BroadcastMessage ();
	void Register_UnityEngine_Coroutine_ReleaseCoroutine ();
	Register_UnityEngine_Coroutine_ReleaseCoroutine ();
	void Register_UnityEngine_Debug_INTERNAL_CALL_DrawLine ();
	Register_UnityEngine_Debug_INTERNAL_CALL_DrawLine ();
	void Register_UnityEngine_Debug_Internal_Log ();
	Register_UnityEngine_Debug_Internal_Log ();
	void Register_UnityEngine_Display_GetSystemExtImpl ();
	Register_UnityEngine_Display_GetSystemExtImpl ();
	void Register_UnityEngine_Display_GetRenderingExtImpl ();
	Register_UnityEngine_Display_GetRenderingExtImpl ();
	void Register_UnityEngine_Display_GetRenderingBuffersImpl ();
	Register_UnityEngine_Display_GetRenderingBuffersImpl ();
	void Register_UnityEngine_Display_SetRenderingResolutionImpl ();
	Register_UnityEngine_Display_SetRenderingResolutionImpl ();
	void Register_UnityEngine_Event_Init ();
	Register_UnityEngine_Event_Init ();
	void Register_UnityEngine_Event_Cleanup ();
	Register_UnityEngine_Event_Cleanup ();
	void Register_UnityEngine_Event_InitCopy ();
	Register_UnityEngine_Event_InitCopy ();
	void Register_UnityEngine_Event_InitPtr ();
	Register_UnityEngine_Event_InitPtr ();
	void Register_UnityEngine_Event_get_rawType ();
	Register_UnityEngine_Event_get_rawType ();
	void Register_UnityEngine_Event_get_type ();
	Register_UnityEngine_Event_get_type ();
	void Register_UnityEngine_Event_set_type ();
	Register_UnityEngine_Event_set_type ();
	void Register_UnityEngine_Event_GetTypeForControl ();
	Register_UnityEngine_Event_GetTypeForControl ();
	void Register_UnityEngine_Event_INTERNAL_CALL_Internal_SetMousePosition ();
	Register_UnityEngine_Event_INTERNAL_CALL_Internal_SetMousePosition ();
	void Register_UnityEngine_Event_Internal_GetMousePosition ();
	Register_UnityEngine_Event_Internal_GetMousePosition ();
	void Register_UnityEngine_Event_INTERNAL_CALL_Internal_SetMouseDelta ();
	Register_UnityEngine_Event_INTERNAL_CALL_Internal_SetMouseDelta ();
	void Register_UnityEngine_Event_Internal_GetMouseDelta ();
	Register_UnityEngine_Event_Internal_GetMouseDelta ();
	void Register_UnityEngine_Event_get_button ();
	Register_UnityEngine_Event_get_button ();
	void Register_UnityEngine_Event_set_button ();
	Register_UnityEngine_Event_set_button ();
	void Register_UnityEngine_Event_get_modifiers ();
	Register_UnityEngine_Event_get_modifiers ();
	void Register_UnityEngine_Event_set_modifiers ();
	Register_UnityEngine_Event_set_modifiers ();
	void Register_UnityEngine_Event_get_pressure ();
	Register_UnityEngine_Event_get_pressure ();
	void Register_UnityEngine_Event_set_pressure ();
	Register_UnityEngine_Event_set_pressure ();
	void Register_UnityEngine_Event_get_clickCount ();
	Register_UnityEngine_Event_get_clickCount ();
	void Register_UnityEngine_Event_set_clickCount ();
	Register_UnityEngine_Event_set_clickCount ();
	void Register_UnityEngine_Event_get_character ();
	Register_UnityEngine_Event_get_character ();
	void Register_UnityEngine_Event_set_character ();
	Register_UnityEngine_Event_set_character ();
	void Register_UnityEngine_Event_get_commandName ();
	Register_UnityEngine_Event_get_commandName ();
	void Register_UnityEngine_Event_set_commandName ();
	Register_UnityEngine_Event_set_commandName ();
	void Register_UnityEngine_Event_get_keyCode ();
	Register_UnityEngine_Event_get_keyCode ();
	void Register_UnityEngine_Event_set_keyCode ();
	Register_UnityEngine_Event_set_keyCode ();
	void Register_UnityEngine_Event_Internal_SetNativeEvent ();
	Register_UnityEngine_Event_Internal_SetNativeEvent ();
	void Register_UnityEngine_Event_Use ();
	Register_UnityEngine_Event_Use ();
	void Register_UnityEngine_Font_Internal_CreateFont ();
	Register_UnityEngine_Font_Internal_CreateFont ();
	void Register_UnityEngine_Font_get_material ();
	Register_UnityEngine_Font_get_material ();
	void Register_UnityEngine_Font_set_material ();
	Register_UnityEngine_Font_set_material ();
	void Register_UnityEngine_Font_HasCharacter ();
	Register_UnityEngine_Font_HasCharacter ();
	void Register_UnityEngine_Font_get_fontNames ();
	Register_UnityEngine_Font_get_fontNames ();
	void Register_UnityEngine_Font_set_fontNames ();
	Register_UnityEngine_Font_set_fontNames ();
	void Register_UnityEngine_Font_get_characterInfo ();
	Register_UnityEngine_Font_get_characterInfo ();
	void Register_UnityEngine_Font_set_characterInfo ();
	Register_UnityEngine_Font_set_characterInfo ();
	void Register_UnityEngine_Font_RequestCharactersInTexture ();
	Register_UnityEngine_Font_RequestCharactersInTexture ();
	void Register_UnityEngine_Font_GetCharacterInfo ();
	Register_UnityEngine_Font_GetCharacterInfo ();
	void Register_UnityEngine_GameObject_SampleAnimation ();
	Register_UnityEngine_GameObject_SampleAnimation ();
	void Register_UnityEngine_GameObject_CreatePrimitive ();
	Register_UnityEngine_GameObject_CreatePrimitive ();
	void Register_UnityEngine_GameObject_GetComponent ();
	Register_UnityEngine_GameObject_GetComponent ();
	void Register_UnityEngine_GameObject_GetComponentByName ();
	Register_UnityEngine_GameObject_GetComponentByName ();
	void Register_UnityEngine_GameObject_get_isStatic ();
	Register_UnityEngine_GameObject_get_isStatic ();
	void Register_UnityEngine_GameObject_set_isStatic ();
	Register_UnityEngine_GameObject_set_isStatic ();
	void Register_UnityEngine_GameObject_get_isStaticBatchable ();
	Register_UnityEngine_GameObject_get_isStaticBatchable ();
	void Register_UnityEngine_GameObject_GetComponentsInternal ();
	Register_UnityEngine_GameObject_GetComponentsInternal ();
	void Register_UnityEngine_GameObject_get_transform ();
	Register_UnityEngine_GameObject_get_transform ();
	void Register_UnityEngine_GameObject_get_rigidbody ();
	Register_UnityEngine_GameObject_get_rigidbody ();
	void Register_UnityEngine_GameObject_get_rigidbody2D ();
	Register_UnityEngine_GameObject_get_rigidbody2D ();
	void Register_UnityEngine_GameObject_get_camera ();
	Register_UnityEngine_GameObject_get_camera ();
	void Register_UnityEngine_GameObject_get_light ();
	Register_UnityEngine_GameObject_get_light ();
	void Register_UnityEngine_GameObject_get_animation ();
	Register_UnityEngine_GameObject_get_animation ();
	void Register_UnityEngine_GameObject_get_constantForce ();
	Register_UnityEngine_GameObject_get_constantForce ();
	void Register_UnityEngine_GameObject_get_renderer ();
	Register_UnityEngine_GameObject_get_renderer ();
	void Register_UnityEngine_GameObject_get_audio ();
	Register_UnityEngine_GameObject_get_audio ();
	void Register_UnityEngine_GameObject_get_guiText ();
	Register_UnityEngine_GameObject_get_guiText ();
	void Register_UnityEngine_GameObject_get_networkView ();
	Register_UnityEngine_GameObject_get_networkView ();
	void Register_UnityEngine_GameObject_get_guiElement ();
	Register_UnityEngine_GameObject_get_guiElement ();
	void Register_UnityEngine_GameObject_get_guiTexture ();
	Register_UnityEngine_GameObject_get_guiTexture ();
	void Register_UnityEngine_GameObject_get_collider ();
	Register_UnityEngine_GameObject_get_collider ();
	void Register_UnityEngine_GameObject_get_collider2D ();
	Register_UnityEngine_GameObject_get_collider2D ();
	void Register_UnityEngine_GameObject_get_hingeJoint ();
	Register_UnityEngine_GameObject_get_hingeJoint ();
	void Register_UnityEngine_GameObject_get_particleEmitter ();
	Register_UnityEngine_GameObject_get_particleEmitter ();
	void Register_UnityEngine_GameObject_get_particleSystem ();
	Register_UnityEngine_GameObject_get_particleSystem ();
	void Register_UnityEngine_GameObject_get_layer ();
	Register_UnityEngine_GameObject_get_layer ();
	void Register_UnityEngine_GameObject_set_layer ();
	Register_UnityEngine_GameObject_set_layer ();
	void Register_UnityEngine_GameObject_get_active ();
	Register_UnityEngine_GameObject_get_active ();
	void Register_UnityEngine_GameObject_set_active ();
	Register_UnityEngine_GameObject_set_active ();
	void Register_UnityEngine_GameObject_SetActive ();
	Register_UnityEngine_GameObject_SetActive ();
	void Register_UnityEngine_GameObject_get_activeSelf ();
	Register_UnityEngine_GameObject_get_activeSelf ();
	void Register_UnityEngine_GameObject_get_activeInHierarchy ();
	Register_UnityEngine_GameObject_get_activeInHierarchy ();
	void Register_UnityEngine_GameObject_SetActiveRecursively ();
	Register_UnityEngine_GameObject_SetActiveRecursively ();
	void Register_UnityEngine_GameObject_get_tag ();
	Register_UnityEngine_GameObject_get_tag ();
	void Register_UnityEngine_GameObject_set_tag ();
	Register_UnityEngine_GameObject_set_tag ();
	void Register_UnityEngine_GameObject_CompareTag ();
	Register_UnityEngine_GameObject_CompareTag ();
	void Register_UnityEngine_GameObject_FindGameObjectWithTag ();
	Register_UnityEngine_GameObject_FindGameObjectWithTag ();
	void Register_UnityEngine_GameObject_FindGameObjectsWithTag ();
	Register_UnityEngine_GameObject_FindGameObjectsWithTag ();
	void Register_UnityEngine_GameObject_SendMessageUpwards ();
	Register_UnityEngine_GameObject_SendMessageUpwards ();
	void Register_UnityEngine_GameObject_SendMessage ();
	Register_UnityEngine_GameObject_SendMessage ();
	void Register_UnityEngine_GameObject_BroadcastMessage ();
	Register_UnityEngine_GameObject_BroadcastMessage ();
	void Register_UnityEngine_GameObject_AddComponent ();
	Register_UnityEngine_GameObject_AddComponent ();
	void Register_UnityEngine_GameObject_Internal_AddComponentWithType ();
	Register_UnityEngine_GameObject_Internal_AddComponentWithType ();
	void Register_UnityEngine_GameObject_Internal_CreateGameObject ();
	Register_UnityEngine_GameObject_Internal_CreateGameObject ();
	void Register_UnityEngine_GameObject_PlayAnimation ();
	Register_UnityEngine_GameObject_PlayAnimation ();
	void Register_UnityEngine_GameObject_StopAnimation ();
	Register_UnityEngine_GameObject_StopAnimation ();
	void Register_UnityEngine_GameObject_Find ();
	Register_UnityEngine_GameObject_Find ();
	void Register_UnityEngine_Gizmos_INTERNAL_CALL_DrawLine ();
	Register_UnityEngine_Gizmos_INTERNAL_CALL_DrawLine ();
	void Register_UnityEngine_Gizmos_INTERNAL_get_color ();
	Register_UnityEngine_Gizmos_INTERNAL_get_color ();
	void Register_UnityEngine_Gizmos_INTERNAL_set_color ();
	Register_UnityEngine_Gizmos_INTERNAL_set_color ();
	void Register_UnityEngine_GL_INTERNAL_CALL_Internal_Clear ();
	Register_UnityEngine_GL_INTERNAL_CALL_Internal_Clear ();
	void Register_UnityEngine_Gradient_Init ();
	Register_UnityEngine_Gradient_Init ();
	void Register_UnityEngine_Gradient_Cleanup ();
	Register_UnityEngine_Gradient_Cleanup ();
	void Register_UnityEngine_Gradient_Evaluate ();
	Register_UnityEngine_Gradient_Evaluate ();
	void Register_UnityEngine_Gradient_get_colorKeys ();
	Register_UnityEngine_Gradient_get_colorKeys ();
	void Register_UnityEngine_Gradient_set_colorKeys ();
	Register_UnityEngine_Gradient_set_colorKeys ();
	void Register_UnityEngine_Gradient_get_alphaKeys ();
	Register_UnityEngine_Gradient_get_alphaKeys ();
	void Register_UnityEngine_Gradient_set_alphaKeys ();
	Register_UnityEngine_Gradient_set_alphaKeys ();
	void Register_UnityEngine_Gradient_SetKeys ();
	Register_UnityEngine_Gradient_SetKeys ();
	void Register_UnityEngine_Graphics_DrawTexture ();
	Register_UnityEngine_Graphics_DrawTexture ();
	void Register_UnityEngine_Graphics_Blit ();
	Register_UnityEngine_Graphics_Blit ();
	void Register_UnityEngine_Graphics_Internal_BlitMaterial ();
	Register_UnityEngine_Graphics_Internal_BlitMaterial ();
	void Register_UnityEngine_Graphics_Internal_BlitMultiTap ();
	Register_UnityEngine_Graphics_Internal_BlitMultiTap ();
	void Register_UnityEngine_GUI_INTERNAL_get_color ();
	Register_UnityEngine_GUI_INTERNAL_get_color ();
	void Register_UnityEngine_GUI_INTERNAL_set_color ();
	Register_UnityEngine_GUI_INTERNAL_set_color ();
	void Register_UnityEngine_GUI_INTERNAL_get_backgroundColor ();
	Register_UnityEngine_GUI_INTERNAL_get_backgroundColor ();
	void Register_UnityEngine_GUI_INTERNAL_set_backgroundColor ();
	Register_UnityEngine_GUI_INTERNAL_set_backgroundColor ();
	void Register_UnityEngine_GUI_INTERNAL_get_contentColor ();
	Register_UnityEngine_GUI_INTERNAL_get_contentColor ();
	void Register_UnityEngine_GUI_INTERNAL_set_contentColor ();
	Register_UnityEngine_GUI_INTERNAL_set_contentColor ();
	void Register_UnityEngine_GUI_get_changed ();
	Register_UnityEngine_GUI_get_changed ();
	void Register_UnityEngine_GUI_set_changed ();
	Register_UnityEngine_GUI_set_changed ();
	void Register_UnityEngine_GUI_get_enabled ();
	Register_UnityEngine_GUI_get_enabled ();
	void Register_UnityEngine_GUI_set_enabled ();
	Register_UnityEngine_GUI_set_enabled ();
	void Register_UnityEngine_GUI_Internal_GetTooltip ();
	Register_UnityEngine_GUI_Internal_GetTooltip ();
	void Register_UnityEngine_GUI_Internal_SetTooltip ();
	Register_UnityEngine_GUI_Internal_SetTooltip ();
	void Register_UnityEngine_GUI_Internal_GetMouseTooltip ();
	Register_UnityEngine_GUI_Internal_GetMouseTooltip ();
	void Register_UnityEngine_GUI_get_depth ();
	Register_UnityEngine_GUI_get_depth ();
	void Register_UnityEngine_GUI_set_depth ();
	Register_UnityEngine_GUI_set_depth ();
	void Register_UnityEngine_GUI_INTERNAL_CALL_DoLabel ();
	Register_UnityEngine_GUI_INTERNAL_CALL_DoLabel ();
	void Register_UnityEngine_GUI_InitializeGUIClipTexture ();
	Register_UnityEngine_GUI_InitializeGUIClipTexture ();
	void Register_UnityEngine_GUI_get_blendMaterial ();
	Register_UnityEngine_GUI_get_blendMaterial ();
	void Register_UnityEngine_GUI_get_blitMaterial ();
	Register_UnityEngine_GUI_get_blitMaterial ();
	void Register_UnityEngine_GUI_INTERNAL_CALL_DoButton ();
	Register_UnityEngine_GUI_INTERNAL_CALL_DoButton ();
	void Register_UnityEngine_GUI_SetNextControlName ();
	Register_UnityEngine_GUI_SetNextControlName ();
	void Register_UnityEngine_GUI_GetNameOfFocusedControl ();
	Register_UnityEngine_GUI_GetNameOfFocusedControl ();
	void Register_UnityEngine_GUI_FocusControl ();
	Register_UnityEngine_GUI_FocusControl ();
	void Register_UnityEngine_GUI_INTERNAL_CALL_DoToggle ();
	Register_UnityEngine_GUI_INTERNAL_CALL_DoToggle ();
	void Register_UnityEngine_GUI_get_usePageScrollbars ();
	Register_UnityEngine_GUI_get_usePageScrollbars ();
	void Register_UnityEngine_GUI_InternalRepaintEditorWindow ();
	Register_UnityEngine_GUI_InternalRepaintEditorWindow ();
	void Register_UnityEngine_GUI_INTERNAL_CALL_DoModalWindow ();
	Register_UnityEngine_GUI_INTERNAL_CALL_DoModalWindow ();
	void Register_UnityEngine_GUI_INTERNAL_CALL_DoWindow ();
	Register_UnityEngine_GUI_INTERNAL_CALL_DoWindow ();
	void Register_UnityEngine_GUI_INTERNAL_CALL_DragWindow ();
	Register_UnityEngine_GUI_INTERNAL_CALL_DragWindow ();
	void Register_UnityEngine_GUI_BringWindowToFront ();
	Register_UnityEngine_GUI_BringWindowToFront ();
	void Register_UnityEngine_GUI_BringWindowToBack ();
	Register_UnityEngine_GUI_BringWindowToBack ();
	void Register_UnityEngine_GUI_FocusWindow ();
	Register_UnityEngine_GUI_FocusWindow ();
	void Register_UnityEngine_GUI_UnfocusWindow ();
	Register_UnityEngine_GUI_UnfocusWindow ();
	void Register_UnityEngine_GUI_Internal_BeginWindows ();
	Register_UnityEngine_GUI_Internal_BeginWindows ();
	void Register_UnityEngine_GUI_Internal_EndWindows ();
	Register_UnityEngine_GUI_Internal_EndWindows ();
	void Register_UnityEngine_GUIClip_INTERNAL_CALL_Push ();
	Register_UnityEngine_GUIClip_INTERNAL_CALL_Push ();
	void Register_UnityEngine_GUIClip_Pop ();
	Register_UnityEngine_GUIClip_Pop ();
	void Register_UnityEngine_GUIClip_INTERNAL_CALL_Unclip_Vector2 ();
	Register_UnityEngine_GUIClip_INTERNAL_CALL_Unclip_Vector2 ();
	void Register_UnityEngine_GUIClip_INTERNAL_CALL_Clip_Vector2 ();
	Register_UnityEngine_GUIClip_INTERNAL_CALL_Clip_Vector2 ();
	void Register_UnityEngine_GUIClip_GetMatrix ();
	Register_UnityEngine_GUIClip_GetMatrix ();
	void Register_UnityEngine_GUIClip_INTERNAL_CALL_SetMatrix ();
	Register_UnityEngine_GUIClip_INTERNAL_CALL_SetMatrix ();
	void Register_UnityEngine_GUILayer_INTERNAL_CALL_HitTest ();
	Register_UnityEngine_GUILayer_INTERNAL_CALL_HitTest ();
	void Register_UnityEngine_GUILayoutUtility_Internal_GetWindowRect ();
	Register_UnityEngine_GUILayoutUtility_Internal_GetWindowRect ();
	void Register_UnityEngine_GUILayoutUtility_INTERNAL_CALL_Internal_MoveWindow ();
	Register_UnityEngine_GUILayoutUtility_INTERNAL_CALL_Internal_MoveWindow ();
	void Register_UnityEngine_GUISettings_Internal_GetCursorFlashSpeed ();
	Register_UnityEngine_GUISettings_Internal_GetCursorFlashSpeed ();
	void Register_UnityEngine_GUIStyle_Init ();
	Register_UnityEngine_GUIStyle_Init ();
	void Register_UnityEngine_GUIStyle_Cleanup ();
	Register_UnityEngine_GUIStyle_Cleanup ();
	void Register_UnityEngine_GUIStyle_get_name ();
	Register_UnityEngine_GUIStyle_get_name ();
	void Register_UnityEngine_GUIStyle_set_name ();
	Register_UnityEngine_GUIStyle_set_name ();
	void Register_UnityEngine_GUIStyle_GetStyleStatePtr ();
	Register_UnityEngine_GUIStyle_GetStyleStatePtr ();
	void Register_UnityEngine_GUIStyle_GetRectOffsetPtr ();
	Register_UnityEngine_GUIStyle_GetRectOffsetPtr ();
	void Register_UnityEngine_GUIStyle_get_imagePosition ();
	Register_UnityEngine_GUIStyle_get_imagePosition ();
	void Register_UnityEngine_GUIStyle_get_wordWrap ();
	Register_UnityEngine_GUIStyle_get_wordWrap ();
	void Register_UnityEngine_GUIStyle_INTERNAL_get_contentOffset ();
	Register_UnityEngine_GUIStyle_INTERNAL_get_contentOffset ();
	void Register_UnityEngine_GUIStyle_INTERNAL_set_contentOffset ();
	Register_UnityEngine_GUIStyle_INTERNAL_set_contentOffset ();
	void Register_UnityEngine_GUIStyle_INTERNAL_set_Internal_clipOffset ();
	Register_UnityEngine_GUIStyle_INTERNAL_set_Internal_clipOffset ();
	void Register_UnityEngine_GUIStyle_get_fixedWidth ();
	Register_UnityEngine_GUIStyle_get_fixedWidth ();
	void Register_UnityEngine_GUIStyle_get_fixedHeight ();
	Register_UnityEngine_GUIStyle_get_fixedHeight ();
	void Register_UnityEngine_GUIStyle_get_stretchWidth ();
	Register_UnityEngine_GUIStyle_get_stretchWidth ();
	void Register_UnityEngine_GUIStyle_set_stretchWidth ();
	Register_UnityEngine_GUIStyle_set_stretchWidth ();
	void Register_UnityEngine_GUIStyle_get_stretchHeight ();
	Register_UnityEngine_GUIStyle_get_stretchHeight ();
	void Register_UnityEngine_GUIStyle_set_stretchHeight ();
	Register_UnityEngine_GUIStyle_set_stretchHeight ();
	void Register_UnityEngine_GUIStyle_Internal_GetLineHeight ();
	Register_UnityEngine_GUIStyle_Internal_GetLineHeight ();
	void Register_UnityEngine_GUIStyle_GetFontInternal ();
	Register_UnityEngine_GUIStyle_GetFontInternal ();
	void Register_UnityEngine_GUIStyle_Internal_Draw ();
	Register_UnityEngine_GUIStyle_Internal_Draw ();
	void Register_UnityEngine_GUIStyle_INTERNAL_CALL_Internal_Draw2 ();
	Register_UnityEngine_GUIStyle_INTERNAL_CALL_Internal_Draw2 ();
	void Register_UnityEngine_GUIStyle_Internal_GetCursorFlashOffset ();
	Register_UnityEngine_GUIStyle_Internal_GetCursorFlashOffset ();
	void Register_UnityEngine_GUIStyle_INTERNAL_CALL_Internal_DrawCursor ();
	Register_UnityEngine_GUIStyle_INTERNAL_CALL_Internal_DrawCursor ();
	void Register_UnityEngine_GUIStyle_Internal_DrawWithTextSelection ();
	Register_UnityEngine_GUIStyle_Internal_DrawWithTextSelection ();
	void Register_UnityEngine_GUIStyle_SetDefaultFont ();
	Register_UnityEngine_GUIStyle_SetDefaultFont ();
	void Register_UnityEngine_GUIStyle_INTERNAL_CALL_Internal_GetCursorPixelPosition ();
	Register_UnityEngine_GUIStyle_INTERNAL_CALL_Internal_GetCursorPixelPosition ();
	void Register_UnityEngine_GUIStyle_INTERNAL_CALL_Internal_GetCursorStringIndex ();
	Register_UnityEngine_GUIStyle_INTERNAL_CALL_Internal_GetCursorStringIndex ();
	void Register_UnityEngine_GUIStyle_Internal_CalcSize ();
	Register_UnityEngine_GUIStyle_Internal_CalcSize ();
	void Register_UnityEngine_GUIStyle_Internal_CalcHeight ();
	Register_UnityEngine_GUIStyle_Internal_CalcHeight ();
	void Register_UnityEngine_GUIStyle_Internal_CalcMinMaxWidth ();
	Register_UnityEngine_GUIStyle_Internal_CalcMinMaxWidth ();
	void Register_UnityEngine_GUIStyleState_Init ();
	Register_UnityEngine_GUIStyleState_Init ();
	void Register_UnityEngine_GUIStyleState_Cleanup ();
	Register_UnityEngine_GUIStyleState_Cleanup ();
	void Register_UnityEngine_GUIStyleState_GetBackgroundInternal ();
	Register_UnityEngine_GUIStyleState_GetBackgroundInternal ();
	void Register_UnityEngine_GUIStyleState_INTERNAL_set_textColor ();
	Register_UnityEngine_GUIStyleState_INTERNAL_set_textColor ();
	void Register_UnityEngine_GUIText_set_text ();
	Register_UnityEngine_GUIText_set_text ();
	void Register_UnityEngine_GUIText_get_material ();
	Register_UnityEngine_GUIText_get_material ();
	void Register_UnityEngine_GUIUtility_GetControlID ();
	Register_UnityEngine_GUIUtility_GetControlID ();
	void Register_UnityEngine_GUIUtility_INTERNAL_CALL_Internal_GetNextControlID2 ();
	Register_UnityEngine_GUIUtility_INTERNAL_CALL_Internal_GetNextControlID2 ();
	void Register_UnityEngine_GUIUtility_GetPermanentControlID ();
	Register_UnityEngine_GUIUtility_GetPermanentControlID ();
	void Register_UnityEngine_GUIUtility_Internal_GetHotControl ();
	Register_UnityEngine_GUIUtility_Internal_GetHotControl ();
	void Register_UnityEngine_GUIUtility_Internal_SetHotControl ();
	Register_UnityEngine_GUIUtility_Internal_SetHotControl ();
	void Register_UnityEngine_GUIUtility_UpdateUndoName ();
	Register_UnityEngine_GUIUtility_UpdateUndoName ();
	void Register_UnityEngine_GUIUtility_get_keyboardControl ();
	Register_UnityEngine_GUIUtility_get_keyboardControl ();
	void Register_UnityEngine_GUIUtility_set_keyboardControl ();
	Register_UnityEngine_GUIUtility_set_keyboardControl ();
	void Register_UnityEngine_GUIUtility_SetDidGUIWindowsEatLastEvent ();
	Register_UnityEngine_GUIUtility_SetDidGUIWindowsEatLastEvent ();
	void Register_UnityEngine_GUIUtility_get_systemCopyBuffer ();
	Register_UnityEngine_GUIUtility_get_systemCopyBuffer ();
	void Register_UnityEngine_GUIUtility_set_systemCopyBuffer ();
	Register_UnityEngine_GUIUtility_set_systemCopyBuffer ();
	void Register_UnityEngine_GUIUtility_Internal_GetDefaultSkin ();
	Register_UnityEngine_GUIUtility_Internal_GetDefaultSkin ();
	void Register_UnityEngine_GUIUtility_Internal_GetBuiltinSkin ();
	Register_UnityEngine_GUIUtility_Internal_GetBuiltinSkin ();
	void Register_UnityEngine_GUIUtility_Internal_ExitGUI ();
	Register_UnityEngine_GUIUtility_Internal_ExitGUI ();
	void Register_UnityEngine_GUIUtility_Internal_GetGUIDepth ();
	Register_UnityEngine_GUIUtility_Internal_GetGUIDepth ();
	void Register_UnityEngine_GUIUtility_get_mouseUsed ();
	Register_UnityEngine_GUIUtility_get_mouseUsed ();
	void Register_UnityEngine_GUIUtility_set_mouseUsed ();
	Register_UnityEngine_GUIUtility_set_mouseUsed ();
	void Register_UnityEngine_GUIUtility_get_hasModalWindow ();
	Register_UnityEngine_GUIUtility_get_hasModalWindow ();
	void Register_UnityEngine_GUIUtility_get_textFieldInput ();
	Register_UnityEngine_GUIUtility_get_textFieldInput ();
	void Register_UnityEngine_GUIUtility_set_textFieldInput ();
	Register_UnityEngine_GUIUtility_set_textFieldInput ();
	void Register_UnityEngine_Input_GetKeyInt ();
	Register_UnityEngine_Input_GetKeyInt ();
	void Register_UnityEngine_Input_GetKeyUpInt ();
	Register_UnityEngine_Input_GetKeyUpInt ();
	void Register_UnityEngine_Input_GetKeyDownInt ();
	Register_UnityEngine_Input_GetKeyDownInt ();
	void Register_UnityEngine_Input_GetAxis ();
	Register_UnityEngine_Input_GetAxis ();
	void Register_UnityEngine_Input_GetButton ();
	Register_UnityEngine_Input_GetButton ();
	void Register_UnityEngine_Input_GetMouseButton ();
	Register_UnityEngine_Input_GetMouseButton ();
	void Register_UnityEngine_Input_GetMouseButtonDown ();
	Register_UnityEngine_Input_GetMouseButtonDown ();
	void Register_UnityEngine_Input_GetMouseButtonUp ();
	Register_UnityEngine_Input_GetMouseButtonUp ();
	void Register_UnityEngine_Input_get_mousePosition ();
	Register_UnityEngine_Input_get_mousePosition ();
	void Register_UnityEngine_Input_get_inputString ();
	Register_UnityEngine_Input_get_inputString ();
	void Register_UnityEngine_Input_GetTouch ();
	Register_UnityEngine_Input_GetTouch ();
	void Register_UnityEngine_Input_get_touchCount ();
	Register_UnityEngine_Input_get_touchCount ();
	void Register_UnityEngine_Input_set_imeCompositionMode ();
	Register_UnityEngine_Input_set_imeCompositionMode ();
	void Register_UnityEngine_Input_get_compositionString ();
	Register_UnityEngine_Input_get_compositionString ();
	void Register_UnityEngine_Input_INTERNAL_set_compositionCursorPos ();
	Register_UnityEngine_Input_INTERNAL_set_compositionCursorPos ();
	void Register_UnityEngine_iPhoneKeyboard_Destroy ();
	Register_UnityEngine_iPhoneKeyboard_Destroy ();
	void Register_UnityEngine_LayerMask_NameToLayer ();
	Register_UnityEngine_LayerMask_NameToLayer ();
	void Register_UnityEngine_Light_INTERNAL_get_color ();
	Register_UnityEngine_Light_INTERNAL_get_color ();
	void Register_UnityEngine_Light_INTERNAL_set_color ();
	Register_UnityEngine_Light_INTERNAL_set_color ();
	void Register_UnityEngine_Light_get_intensity ();
	Register_UnityEngine_Light_get_intensity ();
	void Register_UnityEngine_Light_set_intensity ();
	Register_UnityEngine_Light_set_intensity ();
	void Register_UnityEngine_Material_get_shader ();
	Register_UnityEngine_Material_get_shader ();
	void Register_UnityEngine_Material_set_shader ();
	Register_UnityEngine_Material_set_shader ();
	void Register_UnityEngine_Material_INTERNAL_CALL_SetColor ();
	Register_UnityEngine_Material_INTERNAL_CALL_SetColor ();
	void Register_UnityEngine_Material_GetColor ();
	Register_UnityEngine_Material_GetColor ();
	void Register_UnityEngine_Material_SetTexture ();
	Register_UnityEngine_Material_SetTexture ();
	void Register_UnityEngine_Material_GetTexture ();
	Register_UnityEngine_Material_GetTexture ();
	void Register_UnityEngine_Material_INTERNAL_CALL_SetTextureOffset ();
	Register_UnityEngine_Material_INTERNAL_CALL_SetTextureOffset ();
	void Register_UnityEngine_Material_INTERNAL_CALL_SetTextureScale ();
	Register_UnityEngine_Material_INTERNAL_CALL_SetTextureScale ();
	void Register_UnityEngine_Material_INTERNAL_CALL_SetMatrix ();
	Register_UnityEngine_Material_INTERNAL_CALL_SetMatrix ();
	void Register_UnityEngine_Material_SetFloat ();
	Register_UnityEngine_Material_SetFloat ();
	void Register_UnityEngine_Material_HasProperty ();
	Register_UnityEngine_Material_HasProperty ();
	void Register_UnityEngine_Material_get_renderQueue ();
	Register_UnityEngine_Material_get_renderQueue ();
	void Register_UnityEngine_Material_set_renderQueue ();
	Register_UnityEngine_Material_set_renderQueue ();
	void Register_UnityEngine_Material_Internal_CreateWithShader ();
	Register_UnityEngine_Material_Internal_CreateWithShader ();
	void Register_UnityEngine_Material_Internal_CreateWithMaterial ();
	Register_UnityEngine_Material_Internal_CreateWithMaterial ();
	void Register_UnityEngine_Material_CopyPropertiesFromMaterial ();
	Register_UnityEngine_Material_CopyPropertiesFromMaterial ();
	void Register_UnityEngine_Matrix4x4_INTERNAL_CALL_TRS ();
	Register_UnityEngine_Matrix4x4_INTERNAL_CALL_TRS ();
	void Register_UnityEngine_Mesh_Internal_Create ();
	Register_UnityEngine_Mesh_Internal_Create ();
	void Register_UnityEngine_Mesh_Clear ();
	Register_UnityEngine_Mesh_Clear ();
	void Register_UnityEngine_Mesh_get_isReadable ();
	Register_UnityEngine_Mesh_get_isReadable ();
	void Register_UnityEngine_Mesh_get_canAccess ();
	Register_UnityEngine_Mesh_get_canAccess ();
	void Register_UnityEngine_Mesh_get_vertices ();
	Register_UnityEngine_Mesh_get_vertices ();
	void Register_UnityEngine_Mesh_set_vertices ();
	Register_UnityEngine_Mesh_set_vertices ();
	void Register_UnityEngine_Mesh_get_normals ();
	Register_UnityEngine_Mesh_get_normals ();
	void Register_UnityEngine_Mesh_set_normals ();
	Register_UnityEngine_Mesh_set_normals ();
	void Register_UnityEngine_Mesh_get_tangents ();
	Register_UnityEngine_Mesh_get_tangents ();
	void Register_UnityEngine_Mesh_set_tangents ();
	Register_UnityEngine_Mesh_set_tangents ();
	void Register_UnityEngine_Mesh_get_uv ();
	Register_UnityEngine_Mesh_get_uv ();
	void Register_UnityEngine_Mesh_set_uv ();
	Register_UnityEngine_Mesh_set_uv ();
	void Register_UnityEngine_Mesh_get_uv2 ();
	Register_UnityEngine_Mesh_get_uv2 ();
	void Register_UnityEngine_Mesh_set_uv2 ();
	Register_UnityEngine_Mesh_set_uv2 ();
	void Register_UnityEngine_Mesh_INTERNAL_get_bounds ();
	Register_UnityEngine_Mesh_INTERNAL_get_bounds ();
	void Register_UnityEngine_Mesh_INTERNAL_set_bounds ();
	Register_UnityEngine_Mesh_INTERNAL_set_bounds ();
	void Register_UnityEngine_Mesh_get_colors ();
	Register_UnityEngine_Mesh_get_colors ();
	void Register_UnityEngine_Mesh_set_colors ();
	Register_UnityEngine_Mesh_set_colors ();
	void Register_UnityEngine_Mesh_get_colors32 ();
	Register_UnityEngine_Mesh_get_colors32 ();
	void Register_UnityEngine_Mesh_set_colors32 ();
	Register_UnityEngine_Mesh_set_colors32 ();
	void Register_UnityEngine_Mesh_RecalculateBounds ();
	Register_UnityEngine_Mesh_RecalculateBounds ();
	void Register_UnityEngine_Mesh_RecalculateNormals ();
	Register_UnityEngine_Mesh_RecalculateNormals ();
	void Register_UnityEngine_Mesh_Optimize ();
	Register_UnityEngine_Mesh_Optimize ();
	void Register_UnityEngine_Mesh_get_triangles ();
	Register_UnityEngine_Mesh_get_triangles ();
	void Register_UnityEngine_Mesh_set_triangles ();
	Register_UnityEngine_Mesh_set_triangles ();
	void Register_UnityEngine_Mesh_GetTriangles ();
	Register_UnityEngine_Mesh_GetTriangles ();
	void Register_UnityEngine_Mesh_SetTriangles ();
	Register_UnityEngine_Mesh_SetTriangles ();
	void Register_UnityEngine_Mesh_GetIndices ();
	Register_UnityEngine_Mesh_GetIndices ();
	void Register_UnityEngine_Mesh_SetIndices ();
	Register_UnityEngine_Mesh_SetIndices ();
	void Register_UnityEngine_Mesh_GetTopology ();
	Register_UnityEngine_Mesh_GetTopology ();
	void Register_UnityEngine_Mesh_get_vertexCount ();
	Register_UnityEngine_Mesh_get_vertexCount ();
	void Register_UnityEngine_Mesh_get_subMeshCount ();
	Register_UnityEngine_Mesh_get_subMeshCount ();
	void Register_UnityEngine_Mesh_set_subMeshCount ();
	Register_UnityEngine_Mesh_set_subMeshCount ();
	void Register_UnityEngine_Mesh_SetTriangleStrip ();
	Register_UnityEngine_Mesh_SetTriangleStrip ();
	void Register_UnityEngine_Mesh_GetTriangleStrip ();
	Register_UnityEngine_Mesh_GetTriangleStrip ();
	void Register_UnityEngine_Mesh_CombineMeshes ();
	Register_UnityEngine_Mesh_CombineMeshes ();
	void Register_UnityEngine_Mesh_get_boneWeights ();
	Register_UnityEngine_Mesh_get_boneWeights ();
	void Register_UnityEngine_Mesh_set_boneWeights ();
	Register_UnityEngine_Mesh_set_boneWeights ();
	void Register_UnityEngine_Mesh_get_bindposes ();
	Register_UnityEngine_Mesh_get_bindposes ();
	void Register_UnityEngine_Mesh_set_bindposes ();
	Register_UnityEngine_Mesh_set_bindposes ();
	void Register_UnityEngine_Mesh_MarkDynamic ();
	Register_UnityEngine_Mesh_MarkDynamic ();
	void Register_UnityEngine_Mesh_UploadMeshData ();
	Register_UnityEngine_Mesh_UploadMeshData ();
	void Register_UnityEngine_Mesh_get_blendShapeCount ();
	Register_UnityEngine_Mesh_get_blendShapeCount ();
	void Register_UnityEngine_Mesh_GetBlendShapeName ();
	Register_UnityEngine_Mesh_GetBlendShapeName ();
	void Register_UnityEngine_Mesh_GetBlendShapeIndex ();
	Register_UnityEngine_Mesh_GetBlendShapeIndex ();
	void Register_UnityEngine_MeshFilter_get_mesh ();
	Register_UnityEngine_MeshFilter_get_mesh ();
	void Register_UnityEngine_MeshFilter_set_mesh ();
	Register_UnityEngine_MeshFilter_set_mesh ();
	void Register_UnityEngine_MeshFilter_get_sharedMesh ();
	Register_UnityEngine_MeshFilter_get_sharedMesh ();
	void Register_UnityEngine_MonoBehaviour__ctor ();
	Register_UnityEngine_MonoBehaviour__ctor ();
	void Register_UnityEngine_MonoBehaviour_Invoke ();
	Register_UnityEngine_MonoBehaviour_Invoke ();
	void Register_UnityEngine_MonoBehaviour_InvokeRepeating ();
	Register_UnityEngine_MonoBehaviour_InvokeRepeating ();
	void Register_UnityEngine_MonoBehaviour_CancelInvoke ();
	Register_UnityEngine_MonoBehaviour_CancelInvoke ();
	void Register_UnityEngine_MonoBehaviour_IsInvoking ();
	Register_UnityEngine_MonoBehaviour_IsInvoking ();
	void Register_UnityEngine_MonoBehaviour_StartCoroutine_Auto ();
	Register_UnityEngine_MonoBehaviour_StartCoroutine_Auto ();
	void Register_UnityEngine_MonoBehaviour_StartCoroutine ();
	Register_UnityEngine_MonoBehaviour_StartCoroutine ();
	void Register_UnityEngine_MonoBehaviour_StopCoroutine ();
	Register_UnityEngine_MonoBehaviour_StopCoroutine ();
	void Register_UnityEngine_MonoBehaviour_StopAllCoroutines ();
	Register_UnityEngine_MonoBehaviour_StopAllCoroutines ();
	void Register_UnityEngine_MonoBehaviour_set_useGUILayout ();
	Register_UnityEngine_MonoBehaviour_set_useGUILayout ();
	void Register_UnityEngine_Object_CompareBaseObjectsInternal ();
	Register_UnityEngine_Object_CompareBaseObjectsInternal ();
	void Register_UnityEngine_Object_Internal_CloneSingle ();
	Register_UnityEngine_Object_Internal_CloneSingle ();
	void Register_UnityEngine_Object_INTERNAL_CALL_Internal_InstantiateSingle ();
	Register_UnityEngine_Object_INTERNAL_CALL_Internal_InstantiateSingle ();
	void Register_UnityEngine_Object_Destroy ();
	Register_UnityEngine_Object_Destroy ();
	void Register_UnityEngine_Object_DestroyImmediate ();
	Register_UnityEngine_Object_DestroyImmediate ();
	void Register_UnityEngine_Object_FindObjectsOfType ();
	Register_UnityEngine_Object_FindObjectsOfType ();
	void Register_UnityEngine_Object_get_name ();
	Register_UnityEngine_Object_get_name ();
	void Register_UnityEngine_Object_set_name ();
	Register_UnityEngine_Object_set_name ();
	void Register_UnityEngine_Object_DontDestroyOnLoad ();
	Register_UnityEngine_Object_DontDestroyOnLoad ();
	void Register_UnityEngine_Object_set_hideFlags ();
	Register_UnityEngine_Object_set_hideFlags ();
	void Register_UnityEngine_Object_DestroyObject ();
	Register_UnityEngine_Object_DestroyObject ();
	void Register_UnityEngine_Object_ToString ();
	Register_UnityEngine_Object_ToString ();
	void Register_UnityEngine_ParticleAnimator_INTERNAL_get_rndForce ();
	Register_UnityEngine_ParticleAnimator_INTERNAL_get_rndForce ();
	void Register_UnityEngine_ParticleAnimator_INTERNAL_set_rndForce ();
	Register_UnityEngine_ParticleAnimator_INTERNAL_set_rndForce ();
	void Register_UnityEngine_ParticleAnimator_INTERNAL_get_force ();
	Register_UnityEngine_ParticleAnimator_INTERNAL_get_force ();
	void Register_UnityEngine_ParticleAnimator_INTERNAL_set_force ();
	Register_UnityEngine_ParticleAnimator_INTERNAL_set_force ();
	void Register_UnityEngine_ParticleAnimator_set_autodestruct ();
	Register_UnityEngine_ParticleAnimator_set_autodestruct ();
	void Register_UnityEngine_ParticleEmitter_set_emit ();
	Register_UnityEngine_ParticleEmitter_set_emit ();
	void Register_UnityEngine_ParticleEmitter_get_minSize ();
	Register_UnityEngine_ParticleEmitter_get_minSize ();
	void Register_UnityEngine_ParticleEmitter_set_minSize ();
	Register_UnityEngine_ParticleEmitter_set_minSize ();
	void Register_UnityEngine_ParticleEmitter_get_maxSize ();
	Register_UnityEngine_ParticleEmitter_get_maxSize ();
	void Register_UnityEngine_ParticleEmitter_set_maxSize ();
	Register_UnityEngine_ParticleEmitter_set_maxSize ();
	void Register_UnityEngine_ParticleEmitter_get_minEnergy ();
	Register_UnityEngine_ParticleEmitter_get_minEnergy ();
	void Register_UnityEngine_ParticleEmitter_set_minEnergy ();
	Register_UnityEngine_ParticleEmitter_set_minEnergy ();
	void Register_UnityEngine_ParticleEmitter_get_maxEnergy ();
	Register_UnityEngine_ParticleEmitter_get_maxEnergy ();
	void Register_UnityEngine_ParticleEmitter_set_maxEnergy ();
	Register_UnityEngine_ParticleEmitter_set_maxEnergy ();
	void Register_UnityEngine_ParticleEmitter_get_minEmission ();
	Register_UnityEngine_ParticleEmitter_get_minEmission ();
	void Register_UnityEngine_ParticleEmitter_set_minEmission ();
	Register_UnityEngine_ParticleEmitter_set_minEmission ();
	void Register_UnityEngine_ParticleEmitter_get_maxEmission ();
	Register_UnityEngine_ParticleEmitter_get_maxEmission ();
	void Register_UnityEngine_ParticleEmitter_set_maxEmission ();
	Register_UnityEngine_ParticleEmitter_set_maxEmission ();
	void Register_UnityEngine_ParticleEmitter_get_emitterVelocityScale ();
	Register_UnityEngine_ParticleEmitter_get_emitterVelocityScale ();
	void Register_UnityEngine_ParticleEmitter_set_emitterVelocityScale ();
	Register_UnityEngine_ParticleEmitter_set_emitterVelocityScale ();
	void Register_UnityEngine_ParticleEmitter_INTERNAL_get_worldVelocity ();
	Register_UnityEngine_ParticleEmitter_INTERNAL_get_worldVelocity ();
	void Register_UnityEngine_ParticleEmitter_INTERNAL_set_worldVelocity ();
	Register_UnityEngine_ParticleEmitter_INTERNAL_set_worldVelocity ();
	void Register_UnityEngine_ParticleEmitter_INTERNAL_get_localVelocity ();
	Register_UnityEngine_ParticleEmitter_INTERNAL_get_localVelocity ();
	void Register_UnityEngine_ParticleEmitter_INTERNAL_set_localVelocity ();
	Register_UnityEngine_ParticleEmitter_INTERNAL_set_localVelocity ();
	void Register_UnityEngine_ParticleEmitter_INTERNAL_get_rndVelocity ();
	Register_UnityEngine_ParticleEmitter_INTERNAL_get_rndVelocity ();
	void Register_UnityEngine_ParticleEmitter_INTERNAL_set_rndVelocity ();
	Register_UnityEngine_ParticleEmitter_INTERNAL_set_rndVelocity ();
	void Register_UnityEngine_ParticleEmitter_get_useWorldSpace ();
	Register_UnityEngine_ParticleEmitter_get_useWorldSpace ();
	void Register_UnityEngine_ParticleEmitter_set_useWorldSpace ();
	Register_UnityEngine_ParticleEmitter_set_useWorldSpace ();
	void Register_UnityEngine_ParticleEmitter_get_angularVelocity ();
	Register_UnityEngine_ParticleEmitter_get_angularVelocity ();
	void Register_UnityEngine_ParticleEmitter_set_angularVelocity ();
	Register_UnityEngine_ParticleEmitter_set_angularVelocity ();
	void Register_UnityEngine_ParticleEmitter_get_rndAngularVelocity ();
	Register_UnityEngine_ParticleEmitter_get_rndAngularVelocity ();
	void Register_UnityEngine_ParticleEmitter_set_rndAngularVelocity ();
	Register_UnityEngine_ParticleEmitter_set_rndAngularVelocity ();
	void Register_UnityEngine_ParticleEmitter_get_particles ();
	Register_UnityEngine_ParticleEmitter_get_particles ();
	void Register_UnityEngine_ParticleEmitter_set_particles ();
	Register_UnityEngine_ParticleEmitter_set_particles ();
	void Register_UnityEngine_ParticleEmitter_Emit2 ();
	Register_UnityEngine_ParticleEmitter_Emit2 ();
	void Register_UnityEngine_ParticleEmitter_get_enabled ();
	Register_UnityEngine_ParticleEmitter_get_enabled ();
	void Register_UnityEngine_ParticleRenderer_get_lengthScale ();
	Register_UnityEngine_ParticleRenderer_get_lengthScale ();
	void Register_UnityEngine_ParticleRenderer_set_lengthScale ();
	Register_UnityEngine_ParticleRenderer_set_lengthScale ();
	void Register_UnityEngine_ParticleSystem_get_isPlaying ();
	Register_UnityEngine_ParticleSystem_get_isPlaying ();
	void Register_UnityEngine_ParticleSystem_get_particleCount ();
	Register_UnityEngine_ParticleSystem_get_particleCount ();
	void Register_UnityEngine_ParticleSystem_set_enableEmission ();
	Register_UnityEngine_ParticleSystem_set_enableEmission ();
	void Register_UnityEngine_ParticleSystem_get_emissionRate ();
	Register_UnityEngine_ParticleSystem_get_emissionRate ();
	void Register_UnityEngine_ParticleSystem_set_emissionRate ();
	Register_UnityEngine_ParticleSystem_set_emissionRate ();
	void Register_UnityEngine_ParticleSystem_get_startSpeed ();
	Register_UnityEngine_ParticleSystem_get_startSpeed ();
	void Register_UnityEngine_ParticleSystem_set_startSpeed ();
	Register_UnityEngine_ParticleSystem_set_startSpeed ();
	void Register_UnityEngine_ParticleSystem_get_startSize ();
	Register_UnityEngine_ParticleSystem_get_startSize ();
	void Register_UnityEngine_ParticleSystem_set_startSize ();
	Register_UnityEngine_ParticleSystem_set_startSize ();
	void Register_UnityEngine_ParticleSystem_get_startLifetime ();
	Register_UnityEngine_ParticleSystem_get_startLifetime ();
	void Register_UnityEngine_ParticleSystem_set_startLifetime ();
	Register_UnityEngine_ParticleSystem_set_startLifetime ();
	void Register_UnityEngine_ParticleSystem_SetParticles ();
	Register_UnityEngine_ParticleSystem_SetParticles ();
	void Register_UnityEngine_ParticleSystem_GetParticles ();
	Register_UnityEngine_ParticleSystem_GetParticles ();
	void Register_UnityEngine_ParticleSystem_Internal_Play ();
	Register_UnityEngine_ParticleSystem_Internal_Play ();
	void Register_UnityEngine_ParticleSystem_Internal_IsAlive ();
	Register_UnityEngine_ParticleSystem_Internal_IsAlive ();
	void Register_UnityEngine_ParticleSystem_INTERNAL_CALL_Emit ();
	Register_UnityEngine_ParticleSystem_INTERNAL_CALL_Emit ();
	void Register_UnityEngine_Physics_INTERNAL_get_gravity ();
	Register_UnityEngine_Physics_INTERNAL_get_gravity ();
	void Register_UnityEngine_Physics_INTERNAL_CALL_Internal_Raycast ();
	Register_UnityEngine_Physics_INTERNAL_CALL_Internal_Raycast ();
	void Register_UnityEngine_Physics_INTERNAL_CALL_RaycastAll ();
	Register_UnityEngine_Physics_INTERNAL_CALL_RaycastAll ();
	void Register_UnityEngine_Physics_INTERNAL_CALL_CheckSphere ();
	Register_UnityEngine_Physics_INTERNAL_CALL_CheckSphere ();
	void Register_UnityEngine_Physics2D_INTERNAL_CALL_GetRayIntersectionNonAlloc ();
	Register_UnityEngine_Physics2D_INTERNAL_CALL_GetRayIntersectionNonAlloc ();
	void Register_UnityEngine_PlayerPrefs_TrySetInt ();
	Register_UnityEngine_PlayerPrefs_TrySetInt ();
	void Register_UnityEngine_PlayerPrefs_TrySetFloat ();
	Register_UnityEngine_PlayerPrefs_TrySetFloat ();
	void Register_UnityEngine_PlayerPrefs_TrySetSetString ();
	Register_UnityEngine_PlayerPrefs_TrySetSetString ();
	void Register_UnityEngine_PlayerPrefs_GetInt ();
	Register_UnityEngine_PlayerPrefs_GetInt ();
	void Register_UnityEngine_PlayerPrefs_GetFloat ();
	Register_UnityEngine_PlayerPrefs_GetFloat ();
	void Register_UnityEngine_PlayerPrefs_GetString ();
	Register_UnityEngine_PlayerPrefs_GetString ();
	void Register_UnityEngine_PlayerPrefs_HasKey ();
	Register_UnityEngine_PlayerPrefs_HasKey ();
	void Register_UnityEngine_PlayerPrefs_DeleteKey ();
	Register_UnityEngine_PlayerPrefs_DeleteKey ();
	void Register_UnityEngine_QualitySettings_GetQualityLevel ();
	Register_UnityEngine_QualitySettings_GetQualityLevel ();
	void Register_UnityEngine_QualitySettings_SetQualityLevel ();
	Register_UnityEngine_QualitySettings_SetQualityLevel ();
	void Register_UnityEngine_QualitySettings_get_antiAliasing ();
	Register_UnityEngine_QualitySettings_get_antiAliasing ();
	void Register_UnityEngine_Quaternion_INTERNAL_CALL_AngleAxis ();
	Register_UnityEngine_Quaternion_INTERNAL_CALL_AngleAxis ();
	void Register_UnityEngine_Quaternion_INTERNAL_CALL_FromToRotation ();
	Register_UnityEngine_Quaternion_INTERNAL_CALL_FromToRotation ();
	void Register_UnityEngine_Quaternion_INTERNAL_CALL_LookRotation ();
	Register_UnityEngine_Quaternion_INTERNAL_CALL_LookRotation ();
	void Register_UnityEngine_Quaternion_INTERNAL_CALL_Slerp ();
	Register_UnityEngine_Quaternion_INTERNAL_CALL_Slerp ();
	void Register_UnityEngine_Quaternion_INTERNAL_CALL_Lerp ();
	Register_UnityEngine_Quaternion_INTERNAL_CALL_Lerp ();
	void Register_UnityEngine_Quaternion_INTERNAL_CALL_Inverse ();
	Register_UnityEngine_Quaternion_INTERNAL_CALL_Inverse ();
	void Register_UnityEngine_Quaternion_INTERNAL_CALL_Internal_ToEulerRad ();
	Register_UnityEngine_Quaternion_INTERNAL_CALL_Internal_ToEulerRad ();
	void Register_UnityEngine_Quaternion_INTERNAL_CALL_Internal_FromEulerRad ();
	Register_UnityEngine_Quaternion_INTERNAL_CALL_Internal_FromEulerRad ();
	void Register_UnityEngine_Random_Range ();
	Register_UnityEngine_Random_Range ();
	void Register_UnityEngine_Random_RandomRangeInt ();
	Register_UnityEngine_Random_RandomRangeInt ();
	void Register_UnityEngine_Random_get_value ();
	Register_UnityEngine_Random_get_value ();
	void Register_UnityEngine_RectOffset_Init ();
	Register_UnityEngine_RectOffset_Init ();
	void Register_UnityEngine_RectOffset_Cleanup ();
	Register_UnityEngine_RectOffset_Cleanup ();
	void Register_UnityEngine_RectOffset_get_left ();
	Register_UnityEngine_RectOffset_get_left ();
	void Register_UnityEngine_RectOffset_set_left ();
	Register_UnityEngine_RectOffset_set_left ();
	void Register_UnityEngine_RectOffset_get_right ();
	Register_UnityEngine_RectOffset_get_right ();
	void Register_UnityEngine_RectOffset_set_right ();
	Register_UnityEngine_RectOffset_set_right ();
	void Register_UnityEngine_RectOffset_get_top ();
	Register_UnityEngine_RectOffset_get_top ();
	void Register_UnityEngine_RectOffset_set_top ();
	Register_UnityEngine_RectOffset_set_top ();
	void Register_UnityEngine_RectOffset_get_bottom ();
	Register_UnityEngine_RectOffset_get_bottom ();
	void Register_UnityEngine_RectOffset_set_bottom ();
	Register_UnityEngine_RectOffset_set_bottom ();
	void Register_UnityEngine_RectOffset_get_horizontal ();
	Register_UnityEngine_RectOffset_get_horizontal ();
	void Register_UnityEngine_RectOffset_get_vertical ();
	Register_UnityEngine_RectOffset_get_vertical ();
	void Register_UnityEngine_RectOffset_INTERNAL_CALL_Add ();
	Register_UnityEngine_RectOffset_INTERNAL_CALL_Add ();
	void Register_UnityEngine_RectOffset_INTERNAL_CALL_Remove ();
	Register_UnityEngine_RectOffset_INTERNAL_CALL_Remove ();
	void Register_UnityEngine_Renderer_get_enabled ();
	Register_UnityEngine_Renderer_get_enabled ();
	void Register_UnityEngine_Renderer_set_enabled ();
	Register_UnityEngine_Renderer_set_enabled ();
	void Register_UnityEngine_Renderer_get_material ();
	Register_UnityEngine_Renderer_get_material ();
	void Register_UnityEngine_Renderer_set_material ();
	Register_UnityEngine_Renderer_set_material ();
	void Register_UnityEngine_Renderer_get_sharedMaterial ();
	Register_UnityEngine_Renderer_get_sharedMaterial ();
	void Register_UnityEngine_Renderer_set_sharedMaterial ();
	Register_UnityEngine_Renderer_set_sharedMaterial ();
	void Register_UnityEngine_Renderer_get_sharedMaterials ();
	Register_UnityEngine_Renderer_get_sharedMaterials ();
	void Register_UnityEngine_Renderer_set_sharedMaterials ();
	Register_UnityEngine_Renderer_set_sharedMaterials ();
	void Register_UnityEngine_RenderTexture_GetTemporary ();
	Register_UnityEngine_RenderTexture_GetTemporary ();
	void Register_UnityEngine_RenderTexture_ReleaseTemporary ();
	Register_UnityEngine_RenderTexture_ReleaseTemporary ();
	void Register_UnityEngine_RenderTexture_Internal_GetWidth ();
	Register_UnityEngine_RenderTexture_Internal_GetWidth ();
	void Register_UnityEngine_RenderTexture_Internal_GetHeight ();
	Register_UnityEngine_RenderTexture_Internal_GetHeight ();
	void Register_UnityEngine_RenderTexture_GetColorBuffer ();
	Register_UnityEngine_RenderTexture_GetColorBuffer ();
	void Register_UnityEngine_RenderTexture_GetDepthBuffer ();
	Register_UnityEngine_RenderTexture_GetDepthBuffer ();
	void Register_UnityEngine_RenderTexture_set_active ();
	Register_UnityEngine_RenderTexture_set_active ();
	void Register_UnityEngine_Resources_FindObjectsOfTypeAll ();
	Register_UnityEngine_Resources_FindObjectsOfTypeAll ();
	void Register_UnityEngine_Resources_Load ();
	Register_UnityEngine_Resources_Load ();
	void Register_UnityEngine_Rigidbody_INTERNAL_get_velocity ();
	Register_UnityEngine_Rigidbody_INTERNAL_get_velocity ();
	void Register_UnityEngine_Rigidbody_INTERNAL_set_velocity ();
	Register_UnityEngine_Rigidbody_INTERNAL_set_velocity ();
	void Register_UnityEngine_Rigidbody_get_useGravity ();
	Register_UnityEngine_Rigidbody_get_useGravity ();
	void Register_UnityEngine_Rigidbody_set_useGravity ();
	Register_UnityEngine_Rigidbody_set_useGravity ();
	void Register_UnityEngine_Rigidbody_get_isKinematic ();
	Register_UnityEngine_Rigidbody_get_isKinematic ();
	void Register_UnityEngine_Rigidbody_set_isKinematic ();
	Register_UnityEngine_Rigidbody_set_isKinematic ();
	void Register_UnityEngine_Rigidbody_set_constraints ();
	Register_UnityEngine_Rigidbody_set_constraints ();
	void Register_UnityEngine_Rigidbody_INTERNAL_CALL_AddForce ();
	Register_UnityEngine_Rigidbody_INTERNAL_CALL_AddForce ();
	void Register_UnityEngine_Rigidbody_INTERNAL_get_rotation ();
	Register_UnityEngine_Rigidbody_INTERNAL_get_rotation ();
	void Register_UnityEngine_Rigidbody_INTERNAL_CALL_MoveRotation ();
	Register_UnityEngine_Rigidbody_INTERNAL_CALL_MoveRotation ();
	void Register_UnityEngine_Screen_get_width ();
	Register_UnityEngine_Screen_get_width ();
	void Register_UnityEngine_Screen_get_height ();
	Register_UnityEngine_Screen_get_height ();
	void Register_UnityEngine_Screen_set_orientation ();
	Register_UnityEngine_Screen_set_orientation ();
	void Register_UnityEngine_ScriptableObject_Internal_CreateScriptableObject ();
	Register_UnityEngine_ScriptableObject_Internal_CreateScriptableObject ();
	void Register_UnityEngine_Shader_Find ();
	Register_UnityEngine_Shader_Find ();
	void Register_UnityEngine_Shader_get_isSupported ();
	Register_UnityEngine_Shader_get_isSupported ();
	void Register_UnityEngine_Shader_set_globalMaximumLOD ();
	Register_UnityEngine_Shader_set_globalMaximumLOD ();
	void Register_UnityEngine_Shader_PropertyToID ();
	Register_UnityEngine_Shader_PropertyToID ();
	void Register_UnityEngine_SkinnedMeshRenderer_get_bones ();
	Register_UnityEngine_SkinnedMeshRenderer_get_bones ();
	void Register_UnityEngine_SkinnedMeshRenderer_set_bones ();
	Register_UnityEngine_SkinnedMeshRenderer_set_bones ();
	void Register_UnityEngine_SkinnedMeshRenderer_get_rootBone ();
	Register_UnityEngine_SkinnedMeshRenderer_get_rootBone ();
	void Register_UnityEngine_SkinnedMeshRenderer_set_rootBone ();
	Register_UnityEngine_SkinnedMeshRenderer_set_rootBone ();
	void Register_UnityEngine_SkinnedMeshRenderer_get_quality ();
	Register_UnityEngine_SkinnedMeshRenderer_get_quality ();
	void Register_UnityEngine_SkinnedMeshRenderer_set_quality ();
	Register_UnityEngine_SkinnedMeshRenderer_set_quality ();
	void Register_UnityEngine_SkinnedMeshRenderer_get_sharedMesh ();
	Register_UnityEngine_SkinnedMeshRenderer_get_sharedMesh ();
	void Register_UnityEngine_SkinnedMeshRenderer_set_sharedMesh ();
	Register_UnityEngine_SkinnedMeshRenderer_set_sharedMesh ();
	void Register_UnityEngine_SkinnedMeshRenderer_get_updateWhenOffscreen ();
	Register_UnityEngine_SkinnedMeshRenderer_get_updateWhenOffscreen ();
	void Register_UnityEngine_SkinnedMeshRenderer_set_updateWhenOffscreen ();
	Register_UnityEngine_SkinnedMeshRenderer_set_updateWhenOffscreen ();
	void Register_UnityEngine_SkinnedMeshRenderer_INTERNAL_get_localBounds ();
	Register_UnityEngine_SkinnedMeshRenderer_INTERNAL_get_localBounds ();
	void Register_UnityEngine_SkinnedMeshRenderer_INTERNAL_set_localBounds ();
	Register_UnityEngine_SkinnedMeshRenderer_INTERNAL_set_localBounds ();
	void Register_UnityEngine_SkinnedMeshRenderer_BakeMesh ();
	Register_UnityEngine_SkinnedMeshRenderer_BakeMesh ();
	void Register_UnityEngine_SkinnedMeshRenderer_GetBlendShapeWeight ();
	Register_UnityEngine_SkinnedMeshRenderer_GetBlendShapeWeight ();
	void Register_UnityEngine_SkinnedMeshRenderer_SetBlendShapeWeight ();
	Register_UnityEngine_SkinnedMeshRenderer_SetBlendShapeWeight ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_Authenticate ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_Authenticate ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_Authenticated ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_Authenticated ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_UserName ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_UserName ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_UserID ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_UserID ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_Underage ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_Underage ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_UserImage ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_UserImage ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadFriends ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadFriends ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadAchievementDescriptions ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadAchievementDescriptions ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadAchievements ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadAchievements ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ReportProgress ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ReportProgress ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ReportScore ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ReportScore ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadScores ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadScores ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ShowAchievementsUI ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ShowAchievementsUI ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ShowLeaderboardUI ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ShowLeaderboardUI ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadUsers ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadUsers ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ResetAllAchievements ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ResetAllAchievements ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ShowDefaultAchievementBanner ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ShowDefaultAchievementBanner ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ShowSpecificLeaderboardUI ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ShowSpecificLeaderboardUI ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GcLeaderboard_Internal_LoadScores ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GcLeaderboard_Internal_LoadScores ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GcLeaderboard_Internal_LoadScoresWithUsers ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GcLeaderboard_Internal_LoadScoresWithUsers ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GcLeaderboard_Loading ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GcLeaderboard_Loading ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GcLeaderboard_Dispose ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GcLeaderboard_Dispose ();
	void Register_UnityEngine_SphereCollider_INTERNAL_get_center ();
	Register_UnityEngine_SphereCollider_INTERNAL_get_center ();
	void Register_UnityEngine_SphereCollider_INTERNAL_set_center ();
	Register_UnityEngine_SphereCollider_INTERNAL_set_center ();
	void Register_UnityEngine_Sprite_get_texture ();
	Register_UnityEngine_Sprite_get_texture ();
	void Register_UnityEngine_Sprite_get_textureRect ();
	Register_UnityEngine_Sprite_get_textureRect ();
	void Register_UnityEngine_SystemInfo_get_graphicsShaderLevel ();
	Register_UnityEngine_SystemInfo_get_graphicsShaderLevel ();
	void Register_UnityEngine_SystemInfo_get_supportsImageEffects ();
	Register_UnityEngine_SystemInfo_get_supportsImageEffects ();
	void Register_UnityEngine_SystemInfo_SupportsRenderTextureFormat ();
	Register_UnityEngine_SystemInfo_SupportsRenderTextureFormat ();
	void Register_UnityEngine_TextAsset_get_text ();
	Register_UnityEngine_TextAsset_get_text ();
	void Register_UnityEngine_TextAsset_get_bytes ();
	Register_UnityEngine_TextAsset_get_bytes ();
	void Register_UnityEngine_Texture_Internal_GetWidth ();
	Register_UnityEngine_Texture_Internal_GetWidth ();
	void Register_UnityEngine_Texture_Internal_GetHeight ();
	Register_UnityEngine_Texture_Internal_GetHeight ();
	void Register_UnityEngine_Texture2D_Internal_Create ();
	Register_UnityEngine_Texture2D_Internal_Create ();
	void Register_UnityEngine_Time_get_time ();
	Register_UnityEngine_Time_get_time ();
	void Register_UnityEngine_Time_get_deltaTime ();
	Register_UnityEngine_Time_get_deltaTime ();
	void Register_UnityEngine_Time_get_timeScale ();
	Register_UnityEngine_Time_get_timeScale ();
	void Register_UnityEngine_Time_set_timeScale ();
	Register_UnityEngine_Time_set_timeScale ();
	void Register_UnityEngine_Time_get_frameCount ();
	Register_UnityEngine_Time_get_frameCount ();
	void Register_UnityEngine_Time_get_realtimeSinceStartup ();
	Register_UnityEngine_Time_get_realtimeSinceStartup ();
	void Register_UnityEngine_TouchScreenKeyboard_Destroy ();
	Register_UnityEngine_TouchScreenKeyboard_Destroy ();
	void Register_UnityEngine_TouchScreenKeyboard_TouchScreenKeyboard_InternalConstructorHelper ();
	Register_UnityEngine_TouchScreenKeyboard_TouchScreenKeyboard_InternalConstructorHelper ();
	void Register_UnityEngine_TouchScreenKeyboard_get_text ();
	Register_UnityEngine_TouchScreenKeyboard_get_text ();
	void Register_UnityEngine_TouchScreenKeyboard_set_text ();
	Register_UnityEngine_TouchScreenKeyboard_set_text ();
	void Register_UnityEngine_TouchScreenKeyboard_get_active ();
	Register_UnityEngine_TouchScreenKeyboard_get_active ();
	void Register_UnityEngine_TouchScreenKeyboard_set_active ();
	Register_UnityEngine_TouchScreenKeyboard_set_active ();
	void Register_UnityEngine_TouchScreenKeyboard_get_done ();
	Register_UnityEngine_TouchScreenKeyboard_get_done ();
	void Register_UnityEngine_TouchScreenKeyboard_get_wasCanceled ();
	Register_UnityEngine_TouchScreenKeyboard_get_wasCanceled ();
	void Register_UnityEngine_Transform_INTERNAL_get_position ();
	Register_UnityEngine_Transform_INTERNAL_get_position ();
	void Register_UnityEngine_Transform_INTERNAL_set_position ();
	Register_UnityEngine_Transform_INTERNAL_set_position ();
	void Register_UnityEngine_Transform_INTERNAL_get_localPosition ();
	Register_UnityEngine_Transform_INTERNAL_get_localPosition ();
	void Register_UnityEngine_Transform_INTERNAL_set_localPosition ();
	Register_UnityEngine_Transform_INTERNAL_set_localPosition ();
	void Register_UnityEngine_Transform_INTERNAL_get_localEulerAngles ();
	Register_UnityEngine_Transform_INTERNAL_get_localEulerAngles ();
	void Register_UnityEngine_Transform_INTERNAL_set_localEulerAngles ();
	Register_UnityEngine_Transform_INTERNAL_set_localEulerAngles ();
	void Register_UnityEngine_Transform_INTERNAL_get_rotation ();
	Register_UnityEngine_Transform_INTERNAL_get_rotation ();
	void Register_UnityEngine_Transform_INTERNAL_set_rotation ();
	Register_UnityEngine_Transform_INTERNAL_set_rotation ();
	void Register_UnityEngine_Transform_INTERNAL_get_localRotation ();
	Register_UnityEngine_Transform_INTERNAL_get_localRotation ();
	void Register_UnityEngine_Transform_INTERNAL_set_localRotation ();
	Register_UnityEngine_Transform_INTERNAL_set_localRotation ();
	void Register_UnityEngine_Transform_INTERNAL_get_localScale ();
	Register_UnityEngine_Transform_INTERNAL_get_localScale ();
	void Register_UnityEngine_Transform_INTERNAL_set_localScale ();
	Register_UnityEngine_Transform_INTERNAL_set_localScale ();
	void Register_UnityEngine_Transform_get_parent ();
	Register_UnityEngine_Transform_get_parent ();
	void Register_UnityEngine_Transform_set_parent ();
	Register_UnityEngine_Transform_set_parent ();
	void Register_UnityEngine_Transform_INTERNAL_get_worldToLocalMatrix ();
	Register_UnityEngine_Transform_INTERNAL_get_worldToLocalMatrix ();
	void Register_UnityEngine_Transform_INTERNAL_get_localToWorldMatrix ();
	Register_UnityEngine_Transform_INTERNAL_get_localToWorldMatrix ();
	void Register_UnityEngine_Transform_INTERNAL_CALL_RotateAroundInternal ();
	Register_UnityEngine_Transform_INTERNAL_CALL_RotateAroundInternal ();
	void Register_UnityEngine_Transform_INTERNAL_CALL_LookAt ();
	Register_UnityEngine_Transform_INTERNAL_CALL_LookAt ();
	void Register_UnityEngine_Transform_INTERNAL_CALL_TransformDirection ();
	Register_UnityEngine_Transform_INTERNAL_CALL_TransformDirection ();
	void Register_UnityEngine_Transform_INTERNAL_CALL_InverseTransformDirection ();
	Register_UnityEngine_Transform_INTERNAL_CALL_InverseTransformDirection ();
	void Register_UnityEngine_Transform_INTERNAL_CALL_TransformPoint ();
	Register_UnityEngine_Transform_INTERNAL_CALL_TransformPoint ();
	void Register_UnityEngine_Transform_INTERNAL_CALL_InverseTransformPoint ();
	Register_UnityEngine_Transform_INTERNAL_CALL_InverseTransformPoint ();
	void Register_UnityEngine_Transform_get_root ();
	Register_UnityEngine_Transform_get_root ();
	void Register_UnityEngine_Transform_get_childCount ();
	Register_UnityEngine_Transform_get_childCount ();
	void Register_UnityEngine_Transform_DetachChildren ();
	Register_UnityEngine_Transform_DetachChildren ();
	void Register_UnityEngine_Transform_Find ();
	Register_UnityEngine_Transform_Find ();
	void Register_UnityEngine_Transform_INTERNAL_get_lossyScale ();
	Register_UnityEngine_Transform_INTERNAL_get_lossyScale ();
	void Register_UnityEngine_Transform_IsChildOf ();
	Register_UnityEngine_Transform_IsChildOf ();
	void Register_UnityEngine_Transform_get_hasChanged ();
	Register_UnityEngine_Transform_get_hasChanged ();
	void Register_UnityEngine_Transform_set_hasChanged ();
	Register_UnityEngine_Transform_set_hasChanged ();
	void Register_UnityEngine_Transform_INTERNAL_CALL_RotateAround ();
	Register_UnityEngine_Transform_INTERNAL_CALL_RotateAround ();
	void Register_UnityEngine_Transform_INTERNAL_CALL_RotateAroundLocal ();
	Register_UnityEngine_Transform_INTERNAL_CALL_RotateAroundLocal ();
	void Register_UnityEngine_Transform_GetChild ();
	Register_UnityEngine_Transform_GetChild ();
	void Register_UnityEngine_Transform_GetChildCount ();
	Register_UnityEngine_Transform_GetChildCount ();
	void Register_UnityEngine_UnhandledExceptionHandler_HandleUnhandledException ();
	Register_UnityEngine_UnhandledExceptionHandler_HandleUnhandledException ();
	void Register_UnityEngine_UnityLogWriter_WriteStringToUnityLog ();
	Register_UnityEngine_UnityLogWriter_WriteStringToUnityLog ();
	void Register_UnityEngine_Vector3_INTERNAL_CALL_Slerp ();
	Register_UnityEngine_Vector3_INTERNAL_CALL_Slerp ();
	void Register_UnityEngine_WWW_DestroyWWW ();
	Register_UnityEngine_WWW_DestroyWWW ();
	void Register_UnityEngine_WWW_InitWWW ();
	Register_UnityEngine_WWW_InitWWW ();
	void Register_UnityEngine_WWW_get_bytes ();
	Register_UnityEngine_WWW_get_bytes ();
	void Register_UnityEngine_WWW_GetTexture ();
	Register_UnityEngine_WWW_GetTexture ();
	void Register_UnityEngine_WWW_get_isDone ();
	Register_UnityEngine_WWW_get_isDone ();

}
void RegisterAllClasses() 
{
extern int RegisterClass_GameObject();
RegisterClass_GameObject();
extern int RegisterClass_Component();
RegisterClass_Component();
extern int RegisterClass_LevelGameManager();
RegisterClass_LevelGameManager();
extern int RegisterClass_Transform();
RegisterClass_Transform();
extern int RegisterClass_Behaviour();
RegisterClass_Behaviour();
extern int RegisterClass_GameManager();
RegisterClass_GameManager();
extern int RegisterClass_EditorExtension();
RegisterClass_EditorExtension();
extern int RegisterClass_Camera();
RegisterClass_Camera();
extern int RegisterClass_Material();
RegisterClass_Material();
extern int RegisterClass_MeshRenderer();
RegisterClass_MeshRenderer();
extern int RegisterClass_Renderer();
RegisterClass_Renderer();
extern int RegisterClass_Texture();
RegisterClass_Texture();
extern int RegisterClass_Texture2D();
RegisterClass_Texture2D();
extern int RegisterClass_SceneSettings();
RegisterClass_SceneSettings();
extern int RegisterClass_MeshFilter();
RegisterClass_MeshFilter();
extern int RegisterClass_Mesh();
RegisterClass_Mesh();
extern int RegisterClass_Shader();
RegisterClass_Shader();
extern int RegisterClass_TextAsset();
RegisterClass_TextAsset();
extern int RegisterClass_Rigidbody();
RegisterClass_Rigidbody();
extern int RegisterClass_Collider();
RegisterClass_Collider();
extern int RegisterClass_MeshCollider();
RegisterClass_MeshCollider();
extern int RegisterClass_BoxCollider();
RegisterClass_BoxCollider();
extern int RegisterClass_AnimationClip();
RegisterClass_AnimationClip();
extern int RegisterClass_AudioListener();
RegisterClass_AudioListener();
extern int RegisterClass_AudioClip();
RegisterClass_AudioClip();
extern int RegisterClass_Avatar();
RegisterClass_Avatar();
extern int RegisterClass_AnimatorController();
RegisterClass_AnimatorController();
extern int RegisterClass_RuntimeAnimatorController();
RegisterClass_RuntimeAnimatorController();
extern int RegisterClass_Animator();
RegisterClass_Animator();
extern int RegisterClass_RenderSettings();
RegisterClass_RenderSettings();
extern int RegisterClass_Light();
RegisterClass_Light();
extern int RegisterClass_Animation();
RegisterClass_Animation();
extern int RegisterClass_MonoBehaviour();
RegisterClass_MonoBehaviour();
extern int RegisterClass_MonoScript();
RegisterClass_MonoScript();
extern int RegisterClass_HaloManager();
RegisterClass_HaloManager();
extern int RegisterClass_Font();
RegisterClass_Font();
extern int RegisterClass_NamedObject();
RegisterClass_NamedObject();
extern int RegisterClass_SphereCollider();
RegisterClass_SphereCollider();
extern int RegisterClass_CapsuleCollider();
RegisterClass_CapsuleCollider();
extern int RegisterClass_SkinnedMeshRenderer();
RegisterClass_SkinnedMeshRenderer();
extern int RegisterClass_CharacterController();
RegisterClass_CharacterController();
extern int RegisterClass_LightmapSettings();
RegisterClass_LightmapSettings();
extern int RegisterClass_AudioBehaviour();
RegisterClass_AudioBehaviour();
extern int RegisterClass_NavMeshSettings();
RegisterClass_NavMeshSettings();
extern int RegisterClass_ParticleSystemRenderer();
RegisterClass_ParticleSystemRenderer();
extern int RegisterClass_Motion();
RegisterClass_Motion();
extern int RegisterClass_PreloadData();
RegisterClass_PreloadData();
extern int RegisterClass_Cubemap();
RegisterClass_Cubemap();
extern int RegisterClass_LODGroup();
RegisterClass_LODGroup();
extern int RegisterClass_PhysicsManager();
RegisterClass_PhysicsManager();
extern int RegisterClass_RenderTexture();
RegisterClass_RenderTexture();
extern int RegisterClass_ParticleSystem();
RegisterClass_ParticleSystem();
extern int RegisterClass_TimeManager();
RegisterClass_TimeManager();
extern int RegisterClass_AudioManager();
RegisterClass_AudioManager();
extern int RegisterClass_InputManager();
RegisterClass_InputManager();
extern int RegisterClass_GraphicsSettings();
RegisterClass_GraphicsSettings();
extern int RegisterClass_QualitySettings();
RegisterClass_QualitySettings();
extern int RegisterClass_TagManager();
RegisterClass_TagManager();
extern int RegisterClass_ScriptMapper();
RegisterClass_ScriptMapper();
extern int RegisterClass_DelayedCallManager();
RegisterClass_DelayedCallManager();
extern int RegisterClass_MonoManager();
RegisterClass_MonoManager();
extern int RegisterClass_NavMeshLayers();
RegisterClass_NavMeshLayers();
extern int RegisterClass_PlayerSettings();
RegisterClass_PlayerSettings();
extern int RegisterClass_BuildSettings();
RegisterClass_BuildSettings();
extern int RegisterClass_ResourceManager();
RegisterClass_ResourceManager();
extern int RegisterClass_MasterServerInterface();
RegisterClass_MasterServerInterface();
extern int RegisterClass_AudioSource();
RegisterClass_AudioSource();
extern int RegisterClass_Collider2D();
RegisterClass_Collider2D();
extern int RegisterClass_GUILayer();
RegisterClass_GUILayer();
extern int RegisterClass_GUIText();
RegisterClass_GUIText();
extern int RegisterClass_ParticleAnimator();
RegisterClass_ParticleAnimator();
extern int RegisterClass_ParticleEmitter();
RegisterClass_ParticleEmitter();
extern int RegisterClass_ParticleRenderer();
RegisterClass_ParticleRenderer();
extern int RegisterClass_Sprite();
RegisterClass_Sprite();
extern int RegisterClass_Physics2DSettings();
RegisterClass_Physics2DSettings();
extern int RegisterClass_Rigidbody2D();
RegisterClass_Rigidbody2D();
extern int RegisterClass_Joint2D();
RegisterClass_Joint2D();
extern int RegisterClass_PhysicsMaterial2D();
RegisterClass_PhysicsMaterial2D();

}
